import { AcademyConfig } from './types';

export const raajeevAcademy: AcademyConfig = {
  id: 'raajeev',
  slug: 'raajeev',
  name: 'Raajeev Singh Occult Academy',
  shortName: 'Raajeev Academy',
  instructorName: 'Raajeev Singh Chauhann',
  instructorTitle: 'Founder & Visionary',
  tagline: 'Founder of LEO Family • Celebrity Astrology, Numerology & Vastu Expert',
  description: 'Master Chaldean Numerology, mobile frequency alignment, business branding, and signature corrections directly with Raajeev Singh Chauhann.',
  language: 'English & Hindi',
  branding: {
    logo: '/gemstone-assets/logo.jpg',
    theme: 'maharaja-gold',
    primaryColor: '#F3CD5C',
    secondaryColor: '#D4AF37',
    accentColor: '#34D399',
  },
  assets: {
    heroImage: '/gemstone-assets/background.png',
    profileImage: '/assets/teachers/Raajeev.webp',
    founderPortrait: '/assets/teachers/Raajeev.webp',
    background: '/gemstone-assets/background.png',
    ogImage: '/assets/teachers/Raajeev.webp',
  },
  seo: {
    title: 'Raajeev Singh Chauhann Programs | LEO Family',
    description: 'Discover authentic Numerology, Astrology, Vastu, Gemstones, Name Science and AI-powered spiritual guidance from the experts at LEO Family.',
    keywords: ['Raajeev Singh Chauhann', 'Chaldean Numerology', 'Mobile Numerology', 'Name Correction', 'Astro Numerology'],
    ogImage: '/assets/teachers/Raajeev.webp',
  },
  stats: [
    { value: '20+', label: 'Years Experience', desc: 'Astro-Numerology & Media' },
    { value: '25,000+', label: 'Consultations', desc: 'For Celebrities & Business Brands' },
    { value: '12,000+', label: 'Global Students', desc: 'Across 15+ Countries' },
    { value: '5.0 ★', label: 'Student Reviews', desc: 'Overwhelming Alumnus Trust' },
  ],
  learningRoadmap: [
    { step: '01', title: 'Discover', desc: 'Explore Chaldean numerical frequencies, compound numbers, and birth grid matrices.' },
    { step: '02', title: 'Learn', desc: 'Master name spelling vibrations, mobile number total combinations, and lucky date alignments.' },
    { step: '03', title: 'Practice', desc: 'Analyze real-life horoscopes, active corporate portfolios, and celebrity name shifts.' },
    { step: '04', title: 'Apply', desc: 'Align personal signature spellings, select lucky brand names, and rectify mobile numbers.' },
    { step: '05', title: 'Transform', desc: 'Experience immediate clarity, heightened career flow, and synchronized fortune.' },
    { step: '06', title: 'Guide Others', desc: 'Earn elite certifications to step into professional consulting or elevate your practice.' },
  ],
  whyChooseUs: [
    { title: 'Structured Curriculum', desc: 'Learn step-by-step through scientifically curated progression frameworks.' },
    { title: 'Practical Case Studies', desc: 'Apply teachings on real horoscopes, active brand portfolios, and business layouts.' },
    { title: 'Live Interactive Masterclasses', desc: 'Get immediate personal guidance and live question-and-answer support directly from Raajeev.' },
    { title: 'Lifetime Learning Support', desc: 'Access revised digital guides, continuous updates, and enter our private alumnus community.' },
  ],
  courses: [
    {
      id: 'rj-c1',
      title: 'Complete Chaldean Numerology Masterclass',
      description: 'The definitive masterclass on Chaldean grid calculations. Uncover planetary compound frequencies, name numbers, and birth destiny grids.',
      difficulty: 'All Levels',
      duration: '12 Weeks',
      format: 'Live Online',
      hasCertificate: true,
      instructor: 'Raajeev Singh Chauhann',
      image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80',
      badge: 'Best Seller',
      price: '₹14,999',
    },
    {
      id: 'rj-c2',
      title: 'Mobile Numerology & Digital Vibration',
      description: 'Transform your most frequent digital companion into an active wealth and opportunity magnet with pair combinations.',
      difficulty: 'Beginner',
      duration: '4 Weeks',
      format: 'Self-Paced Video',
      hasCertificate: true,
      instructor: 'Raajeev Singh Chauhann',
      image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
      badge: 'Most Popular',
      price: '₹5,999',
    },
    {
      id: 'rj-c3',
      title: 'Premium Name & Signature Correction',
      description: 'Master the art and science of signature spellings, branding, and trademark correction using advanced Chaldean vibrations.',
      difficulty: 'Advanced',
      duration: '6 Weeks',
      format: 'Hybrid Masterclass',
      hasCertificate: true,
      instructor: 'Raajeev Singh Chauhann',
      image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
      badge: 'Featured',
      price: '₹9,999',
    },
    {
      id: 'rj-c4',
      title: 'Business Numerology & Brand Strategy',
      description: 'Designed exclusively for entrepreneurs. Select powerful trade names, partner shares, and incorporation dates for expansion.',
      difficulty: 'Advanced',
      duration: '8 Weeks',
      format: 'Live Online',
      hasCertificate: true,
      instructor: 'Raajeev Singh Chauhann',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
      badge: 'Advanced',
      price: '₹18,500',
    },
  ],
  testimonials: [
    {
      id: 'rjt1',
      name: 'Ananya Roy',
      role: 'Fashion Designer, Delhi',
      rating: 5,
      content: 'Raajeev Sir’s Chaldean numerology course opened my eyes to the power of sound vibrations. My brand revenue grew 3x after name correction!',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Complete Chaldean Numerology',
    },
    {
      id: 'rjt2',
      name: 'Karan Malhotra',
      role: 'Tech Founder, Bengaluru',
      rating: 5,
      content: 'Changing my mobile number pairs based on Raajeev Sir’s mobile numerology framework brought instant client query flow. Highly recommended!',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Mobile Numerology',
    },
    {
      id: 'rjt3',
      name: 'Priya Sharma',
      role: 'Life Coach, London',
      rating: 5,
      content: 'The depth of knowledge and step-by-step clarity Raajeev Singh Chauhann provides is unmatched anywhere in the world.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Name & Signature Correction',
    },
  ],
  faqs: [
    {
      id: 'rjf1',
      question: 'Why is Chaldean Numerology considered superior to Western Pythagorean systems?',
      answer: 'Chaldean Numerology is based on ancient sacred sound frequencies and vibrational values assigned to letters, reflecting authentic cosmic energy alignments.',
    },
    {
      id: 'rjf2',
      question: 'Will I receive live mentorship from Raajeev Singh Chauhann?',
      answer: 'Yes! Live interactive masterclasses include real-time Q&A sessions directly with Raajeev Sir.',
    },
    {
      id: 'rjf3',
      question: 'Is a certificate provided after course completion?',
      answer: 'Yes, graduates receive an accredited Certificate of Completion from Raajeev Singh Occult Academy upon submitting their final practical assignment.',
    },
  ],
  events: [
    {
      id: 'rje1',
      date: 'Oct 24, 2026',
      time: '7:00 PM IST',
      speaker: 'Raajeev Singh Chauhann',
      topic: 'Vedic Alignment for Business & Brand Success',
      seatsAvailable: 14,
      totalSeats: 100,
      countdownTarget: '2026-10-24T19:00:00',
    },
    {
      id: 'rje2',
      date: 'Nov 08, 2026',
      time: '11:00 AM IST',
      speaker: 'Raajeev Singh Chauhann',
      topic: 'Chaldean Compound Frequencies & Signature Corrections',
      seatsAvailable: 8,
      totalSeats: 75,
      countdownTarget: '2026-11-08T11:00:00',
    },
  ],
  freeResources: [
    {
      id: 'rjr1',
      title: 'The Chaldean Grid Blueprint',
      type: 'eBook',
      description: 'An elegant PDF handbook outlining birth chart mapping, lucky numbers, and compound alignments.',
      downloadUrl: '#',
      image: '/gemstone-assets/background.png',
    },
    {
      id: 'rjr2',
      title: 'Mobile Frequency & Combination Audit',
      type: 'Cheat Sheet',
      description: 'A 5-minute check to identify positive and challenging mobile number digit pairs.',
      downloadUrl: '#',
      image: '/gemstone-assets/ruby.jpg',
    },
  ],
  contactDetails: {
    phone: '+91 99537 13176',
    whatsapp: 'https://wa.me/919953713176',
    email: 'contact@raajeevsingh.com',
    address: 'New Delhi & Mumbai, India',
  },
  socialLinks: {
    youtube: 'https://youtube.com/@raajeevsinghchauhann',
    facebook: 'https://facebook.com/raajeevsinghchauhann',
    instagram: 'https://instagram.com/raajeevsinghchauhann',
  },
};
