import { AcademyConfig } from './types';

export const sannjoyAcademy: AcademyConfig = {
  id: 'sannjoy',
  slug: 'sannjoy',
  name: 'Sannjoy Biswass Academy',
  shortName: 'Sannjoy Biswass Academy',
  instructorName: 'Sannjoy Biswass',
  instructorTitle: 'Numerologist & Vastu Expert',
  instructorBio: 'Sannjoy Biswass is a world-renowned Bengali Master Numerologist and Sacred Frequency Mentor. Over two decades, he has empowered thousands of students across West Bengal, Bangladesh, and globally with practical Chaldean numerology, Lo Shu grid balance, mobile number harmonics, and name spelling remedies.',
  tagline: 'সংখ্যা ও শক্তির সঠিক সামঞ্জস্যে জীবনের পরম উন্মোচন',
  description: 'সঞ্জয় বিশ্বাস অ্যাকাডেমিতে শিখুন বৈদিক ও চালডিয়ান সংখ্যাতত্ত্ব, মোবাইল নিউমেরোলজি, লো শু গ্রিড ও বিজনেস নেম টিউনিং সরাসরি বাংলা ভাষায়।',
  language: 'Bengali (বাংলা)',
  languages: {
    default: 'Bengali (বাংলা)',
    available: ['Bengali (বাংলা)', 'English', 'Hindi', 'Gujarati'],
  },
  hero: {
    title: 'সঞ্জয় বিশ্বাসের সাথে শিখুন খাঁটি বাংলা সংখ্যাতত্ত্ব ও লো শু গ্রিড',
    subtitle: 'আপনার জন্ম তারিখ, নাম এবং মোবাইলের সংখ্যার গোপন কম্পাঙ্ক বিশ্লেষণ করে জীবনের সমৃদ্ধি, সুস্বাস্থ্য এবং সাফল্য অর্জন করুন।',
    ctaText: 'আজই কোর্সে এনরোল করুন',
    secondaryCtaText: 'বিনামূল্যে গাইড ডাউনলোড করুন',
  },
  branding: {
    logo: '/assets/sannjoy/logo.jpg',
    theme: 'bengali-royal-gold',
    primaryColor: '#D4AF37',
    secondaryColor: '#10B981',
    accentColor: '#E11D48',
    courseBanner: '/assets/sannjoy/course_banner.jpg',
  },
  assets: {
    heroImage: '/assets/teachers/sannjoy.webp',
    profileImage: '/assets/teachers/sannjoy.webp',
    founderPortrait: '/assets/teachers/sannjoy.webp',
    background: '/assets/teachers/sannjoy.webp',
    ogImage: '/assets/teachers/sannjoy.webp',
    courseBanner: '/assets/sannjoy/course_banner.jpg',
    dashboardProfile: '/assets/teachers/sannjoy.webp',
    certificateTemplate: '/assets/sannjoy/course_banner.jpg',
    videoPlayerPoster: '/assets/teachers/sannjoy.webp',
    instructorCard: '/assets/teachers/sannjoy.webp',
  },
  contactDetails: {
    phone: '+91 99537 13176',
    whatsapp: 'https://chat.whatsapp.com/Duy1rNPagOD2sQWlNfyMfg',
    email: 'contact@sannjoybiswass.com',
    address: 'Kolkata, West Bengal, India',
  },
  socialLinks: {
    youtube: 'https://youtube.com/@sannjoybiswass',
    facebook: 'https://facebook.com/sannjoybiswass',
    instagram: 'https://instagram.com/sannjoybiswass',
    linkedin: 'https://linkedin.com/in/sannjoybiswass',
    twitter: 'https://twitter.com/sannjoybiswass',
  },
  seo: {
    title: 'Sannjoy Biswass Programs | LEO Family',
    description: 'Discover authentic Numerology, Astrology, Vastu, Gemstones, Name Science and AI-powered spiritual guidance from the experts at LEO Family.',
    keywords: [
      'Sannjoy Biswass',
      'Sannjoy Biswass Academy',
      'Bengali Numerology',
      'বাংলা সংখ্যাতত্ত্ব',
      'Lo Shu Grid Bengali',
      'Mobile Numerology Bengali',
      'Chaldean Numerology Kolkata',
      'Name Numerology Bengali',
      'Bengali Astrologer'
    ],
    ogImage: '/assets/teachers/sannjoy.webp',
    twitterCard: 'summary_large_image',
    siteName: 'Sannjoy Biswass Academy',
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'EducationalOrganization',
      name: 'Sannjoy Biswass Academy',
      alternateName: 'সঞ্জয় বিশ্বাস অ্যাকাডেমি',
      url: 'https://ais-pre-floqmorx3xw43dcnunwbmp-633550351805.asia-southeast1.run.app/academy/sannjoy',
      logo: 'https://ais-pre-floqmorx3xw43dcnunwbmp-633550351805.asia-southeast1.run.app/assets/sannjoy/logo.jpg',
      founder: {
        '@type': 'Person',
        name: 'Sannjoy Biswass',
        jobTitle: 'Master Numerologist'
      },
      description: 'Authentic Bengali Numerology and Lo Shu Grid Science Masterclass',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Kolkata',
        addressRegion: 'West Bengal',
        addressCountry: 'IN'
      }
    },
  },
  stats: [
    { value: '২০+', label: 'বছরের অভিজ্ঞতা', desc: 'সংখ্যাতত্ত্ব ও জ্যোতিষ শাস্ত্র' },
    { value: '১২,৫০০+', label: 'সফল ক্লায়েন্ট', desc: 'ব্যক্তিগত ও ব্যবসায়িক লাইফ গাইডেন্স' },
    { value: '৭,৫০০+', label: 'প্রশিক্ষিত শিক্ষার্থী', desc: 'সার্টিফাইড নিউমেরোলজিস্ট' },
    { value: '৯৯.২%', label: 'সন্তুষ্টির হার', desc: 'সঠিক রেমেডি ও ফলাফল' },
  ],
  learningRoadmap: [
    { step: '০১', title: 'মৌলিক সংখ্যাতত্ত্ব', desc: '১ থেকে ৯ পর্যন্ত গ্রহের প্রভাব এবং চালডিয়ান সংখ্যা পদ্ধতির মূল ভিত্তি।' },
    { step: '০২', title: 'লো শু গ্রিড বিশ্লেষণ', desc: '৩x৩ লো শু গ্রিডের মাধ্যমে জীবনের শক্তি, শারীরিক স্বাস্থ ও আর্থিক যোগ মূল্যায়ন।' },
    { step: '০৩', title: 'মোবাইল নিউমেরোলজি', desc: 'মোবাইল নম্বরের প্রতি জোড়া ডিজিটের কম্পাঙ্ক টিউনিং এবং শুভ সংখ্যা নির্বাচন।' },
    { step: '০৪', title: 'নাম ও সিগনেচার সংশোধন', desc: 'ইংরেজি ও বাংলা বানানের অক্ষরের ভাইব্রেশন সঠিক করে ভাগ্য পরিবর্তন।' },
    { step: '০৫', title: 'বিজনেস ব্র্যান্ডিং', desc: 'কোম্পানির নাম, লোগো এবং পার্টনারশিপ নাম্বার মিলিয়ে আয়ের পথ তৈরি।' },
    { step: '০৬', title: 'প্রফেশনাল কনসালটেন্সি', desc: 'সার্টিফাইড নিউমেরোলজিস্ট হিসেবে নিজের চেম্বার বা অনলাইন ব্র্যান্ড চালু করার কৌশল।' },
  ],
  whyChooseUs: [
    { title: 'সহজ বাংলা ভাষায় পাঠদান', desc: 'জটিল সংস্কৃত ও গাণিতিক সূত্র ছাড়া সহজ সরল বাংলায় সম্পূর্ণ কোর্স।' },
    { title: 'বাস্তব কেস স্টাডি', desc: 'শত শত বিখ্যাত ব্যক্তি ও সাধারণ মানুষের রিয়েল লাইফ জন্ম কুণ্ডলী এবং নাম বিশ্লেষণ।' },
    { title: 'সরাসরি লাইভ সাপোর্ট', desc: 'সঞ্জয় বিশ্বাসের সঙ্গে সরাসরি লাইভ ক্লাসে প্রশ্নোত্তর এবং ব্যক্তিগত সমস্যার সমাধান।' },
    { title: 'সার্টিফিকেট ও আজীবন নেটওয়ার্ক', desc: 'অফিসিয়াল সার্টিফাইড সার্টিফিকেট এবং লাইফটাইম অ্যালুমনি ফোরামে যোগদানের সুযোগ।' },
  ],
  courses: [
    {
      id: 'sb-c1',
      title: 'Advanced Numerology Masterclass (এডভান্সড নিউমেরোলজি)',
      description: 'বাংলা ভাষায় সম্পূর্ণ চালডিয়ান ও বৈদিক সংখ্যাতত্ত্ব। জন্ম তারিখ ও নামের কম্পাঙ্ক বিশ্লেষণের সর্বশ্রেষ্ঠ মাস্টারকোর্স।',
      difficulty: 'All Levels',
      duration: '10 Weeks',
      format: 'Live Online (বাংলা)',
      hasCertificate: true,
      instructor: 'Sannjoy Biswass',
      image: '/assets/sannjoy/course_banner.jpg',
      badge: 'Best Seller',
      price: '₹9,999',
    },
    {
      id: 'sb-c2',
      title: 'Mobile Numerology Science (মোবাইল নিউমেরোলজি)',
      description: 'আপনার মোবাইল নাম্বার কীভাবে আপনার ক্যারিয়ার, সম্পর্ক এবং আর্থিক সাফল্য নির্ধারণ করে তা বিস্তারিত শিখুন।',
      difficulty: 'Beginner',
      duration: '4 Weeks',
      format: 'Self-Paced (বাংলা)',
      hasCertificate: true,
      instructor: 'Sannjoy Biswass',
      image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
      badge: 'Most Popular',
      price: '₹4,999',
    },
    {
      id: 'sb-c3',
      title: 'Name & Signature Corrections (নাম ও সিগনেচার সংশোধন)',
      description: 'সঠিক বানান ও হস্তাক্ষর পরিবর্তনের মাধ্যমে জীবন ও ভাগ্যের ইতিবাচক রূপান্তর ঘটানোর বৈজ্ঞানিক পদ্ধতি।',
      difficulty: 'Intermediate',
      duration: '6 Weeks',
      format: 'Live Online (বাংলা)',
      hasCertificate: true,
      instructor: 'Sannjoy Biswass',
      image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
      badge: 'Featured',
      price: '₹7,499',
    },
    {
      id: 'sb-c4',
      title: 'Lo Shu Grid & Elemental Balance (লো শু গ্রিড বিশ্লেষণ)',
      description: 'চীনা ও ভারতীয় লো শু গ্রিডের ৯টি ঘরের গোপন শক্তি, প্লেন এবং হারানো সংখ্যার নিখুঁত রেমেডি।',
      difficulty: 'Beginner',
      duration: '5 Weeks',
      format: 'Live Online (বাংলা)',
      hasCertificate: true,
      instructor: 'Sannjoy Biswass',
      image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80',
      badge: 'New',
      price: '₹5,999',
    },
    {
      id: 'sb-c5',
      title: 'Business Numerology & Branding (বিজনেস নিউমেরোলজি)',
      description: 'ব্যবসার লোগো, ব্র্যান্ড নেম, ব্যাংক অ্যাকাউন্ট নাম্বার ও পার্টনারশিপ টিউনিংয়ের মাধ্যমে সর্বোচ্চ লাভের কৌশল।',
      difficulty: 'Advanced',
      duration: '8 Weeks',
      format: 'Hybrid Masterclass (বাংলা)',
      hasCertificate: true,
      instructor: 'Sannjoy Biswass',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
      badge: 'Advanced',
      price: '₹12,999',
    },
  ],
  testimonials: [
    {
      id: 'sbt1',
      name: 'সুপ্রিয় মুখোপাধ্যায়',
      role: 'ব্যবসায়ী, কলকাতা',
      rating: 5,
      content: 'সঞ্জয় বিশ্বাস স্যারের মোবাইল নিউমেরোলজি ক্লাস করার পর আমার শোরুমের মোবাইল নাম্বার পরিবর্তনের মাত্র ৩০ দিনের মধ্যে বিক্রি ৪০% বেড়ে গেছে!',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Mobile Numerology Science',
    },
    {
      id: 'sbt2',
      name: 'অর্পিতা ব্যানার্জী',
      role: 'শিক্ষিকা, হাওড়া',
      rating: 5,
      content: 'লো শু গ্রিড ও নাম সংশোধন ক্লাসের পর আমার মেয়ের নাম পরিবর্তন করে যা রেজাল্ট পেয়েছি তা সত্যিই অলৌকিক। সঞ্জয় স্যারকে অসংখ্য ধন্যবাদ।',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Name & Signature Corrections',
    },
    {
      id: 'sbt3',
      name: 'দেবব্রত সেনগুপ্ত',
      role: 'আইটি প্রফেশনাল, শিলিগুড়ি',
      rating: 5,
      content: 'চালডিয়ান নিউমেরোলজি শেখার জন্য সঞ্জয় বিশ্বাস অ্যাকাডেমি সেরা স্থান। প্রতিটি কনসেপ্ট পানির মতো সহজ করে বুঝিয়ে দেওয়া হয়।',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Advanced Numerology Masterclass',
    },
  ],
  faqs: [
    {
      id: 'sbf1',
      question: 'সংখ্যাতত্ত্ব শেখার জন্য কি আগে থেকে গণিত বা জ্যোতিষশাস্ত্র জানা থাকা দরকার?',
      answer: 'একেবারেই না! সঞ্জয় বিশ্বাস স্যার একদম শূন্য থেকে অতি সহজ ভাষায় বাংলায় ক্লাসে ধাপে ধাপে শেখান। কোনো আগের অভিজ্ঞতার প্রয়োজন নেই।',
    },
    {
      id: 'sbf2',
      question: 'ক্লাসগুলো কি বাংলায় হবে নাকি ইংরেজিতে?',
      answer: 'প্রধান কোর্সটি সম্পূর্ণ বাংলা ভাষায় পরিচালিত হবে। পাশাপাশি স্টাডি মেটেরিয়াল বাংলায় এবং ইংরেজিতে দুটি ভাষাতেই পাবেন।',
    },
    {
      id: 'sbf3',
      question: 'কোর্স শেষে কি অফিশিয়াল সার্টিফিকেট দেওয়া হবে?',
      answer: 'হ্যাঁ, কোর্স সম্পন্ন এবং প্রাকটিক্যাল এসাইনমেন্ট জমা দেওয়ার পর আপনাকে সঞ্জয় বিশ্বাস অ্যাকাডেমির থেকে অফিশিয়াল ভেরিফাইড সার্টিফিকেট প্রদান করা হবে।',
    },
  ],
  events: [
    {
      id: 'sbe1',
      date: 'সেপ্টেম্বর ১৪, ২০২৬',
      time: 'সকাল ১১:০০ - দুপুর ০১:০০ (IST)',
      speaker: 'Sannjoy Biswass',
      topic: 'লাইভ মাস্টারক্লাস: মোবাইল নাম্বার কীভাবে ভাগ্য নিয়ন্ত্রণ করে?',
      seatsAvailable: 15,
      totalSeats: 100,
      countdownTarget: '2024-09-14T11:00:00',
    },
    {
      id: 'sbe2',
      date: 'সেপ্টেম্বর ১৪, ২০২৬',
      time: 'সকাল ১১:০০ - দুপুর ০১:০০ (IST)',
      speaker: 'Sannjoy Biswass',
      topic: 'বিশেষ সেশন: লো শু গ্রিডে হারানো সংখ্যার রেমেডি ও বাস্তু কানেকশন',
      seatsAvailable: 20,
      totalSeats: 80,
      countdownTarget: '2024-09-14T11:00:00',
    },
  ],
  freeResources: [
    {
      id: 'sbr1',
      title: 'বাংলা লো শু গ্রিড সেলফ-অডিট চিট শিট',
      type: 'PDF গাইড',
      description: '১০ মিনিটে নিজের জন্ম তারিখ বসিয়ে লো শু গ্রিড তৈরি ও বিশ্লেষণ করার ফ্রি গাইড বুক।',
      downloadUrl: '#',
      image: '/assets/sannjoy/course_banner.jpg',
    },
    {
      id: 'sbr2',
      title: 'মোবাইল নাম্বার শুভ সংখ্যা গাইড বুক',
      type: 'ই-বুক',
      description: 'কোন ডিজিটের জোড়া আপনার জন্য শুভ এবং কোনটি ক্ষতিকর তা জানার গাইড।',
      downloadUrl: '#',
      image: '/assets/sannjoy/hero.png',
    },
  ],
  translations: {
    bn: {
      academyName: 'সঞ্জয় বিশ্বাস অ্যাকাডেমি',
      instructorName: 'সঞ্জয় বিশ্বাস',
      instructorTitle: 'মাস্টার নিউমেরোলজিস্ট এবং বৈদিক সংখ্যাতত্ত্ব বিশেষজ্ঞ',
      enrollNow: 'আজই এনরোল করুন',
      learnMore: 'বিস্তারিত জানুন',
      welcome: 'স্বাগতম',
      catalog: 'কোর্স ক্যাটালগ',
    },
    en: {
      academyName: 'Sannjoy Biswass Academy',
      instructorName: 'Sannjoy Biswass',
      instructorTitle: 'Master Numerologist & Sacred Frequency Mentor',
      enrollNow: 'Enroll Now',
      learnMore: 'Learn More',
      welcome: 'Welcome',
      catalog: 'Course Catalog',
    }
  }
};
