import { AcademyConfig } from './types';
import { Assets } from '../assets';

export const shaunakAcademy: AcademyConfig = {
  id: 'shaunak',
  slug: 'shaunak',
  name: 'Shaunak S. Patthak Academy',
  shortName: 'Shaunak Academy',
  instructorName: 'Shaunak S. Patthak',
  instructorTitle: 'Numerology & Vastu Expert',
  tagline: 'Senior Faculty • Gujrati Learning Mentor',
  description: 'Experience the powerful harmony of your Birth Chart, Dashas, Planetary Transits, and sacred guidance with Shaunak S. Patthak.',
  language: 'English & Hinglish',
  branding: {
    logo: '/gemstone-assets/logo.jpg',
    theme: 'cosmic-purple',
    primaryColor: '#8B5CF6',
    secondaryColor: '#D8B4FE',
    accentColor: '#F59E0B',
  },
  assets: {
    heroImage: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=1200&q=80',
    profileImage: Assets.teachers.shaunak.image,
    founderPortrait: Assets.teachers.shaunak.image,
    background: '/gemstone-assets/background.png',
    ogImage: Assets.teachers.shaunak.image,
  },
  seo: {
    title: 'Shaunak S. Patthak Programs | LEO Family',
    description: 'Discover authentic Numerology, Astrology, Vastu, Gemstones, Name Science and AI-powered spiritual guidance from the experts at LEO Family.',
    keywords: ['Shaunak S. Patthak', 'Numerology', 'Vedic Astrology', 'Dasha Calculations', 'Planetary Remedies'],
    ogImage: Assets.teachers.shaunak.image,
  },
  stats: [
    { value: '10+', label: 'Years Experience', desc: 'Numerology Research & Mobile, Name Analysis' },
    { value: '15,000+', label: 'Charts Read', desc: 'Global Business & Political Leaders' },
    { value: '6,200+', label: 'Alumni Scholars', desc: 'Certified Astro-Vastu Mentors' },
    { value: '100%', label: 'Scriptural Rigor', desc: 'Classical Vedic Authenticity' },
  ],
  learningRoadmap: [
    { step: '01', title: 'Kundali Decipher', desc: 'Decode the 12 houses, planetary lordships, and Lagna charts.' },
    { step: '02', title: 'Dasha Precision', desc: 'Calculate Vimshottari Dasha cycles and transit triggers for precise life timing.' },
    { step: '03', title: 'Astro-Vastu Overlay', desc: 'Superimpose birth chart planetary degrees onto physical building grids.' },
    { step: '04', title: 'Gemstone & Mantras', desc: 'Select authentic planetary gems, rudrakshas, and Vedic resonance chants.' },
    { step: '05', title: 'Predictive Mastery', desc: 'Master career, relationship, wealth, and health prediction matrices.' },
    { step: '06', title: 'Professional Scholar', desc: 'Establish a high-trust Vedic astrology practice certified by Shaunak S. Patthak Academy.' },
  ],
  whyChooseUs: [
    { title: 'Classical Vedic Authenticity', desc: 'Rooted directly in ancient Brihat Parashara and Varahamihira scriptures.' },
    { title: 'Astro-Vastu Synergy', desc: 'Unique framework combining individual horoscope transits with home directional energy.' },
    { title: 'Interactive Chart Worksheets', desc: 'Practice analyzing real horoscopes of celebrities, business founders, and historical figures.' },
    { title: 'Dedicated Mentorship Circle', desc: 'Direct live case review sessions with Shaunak S. Patthak to hone predictive accuracy.' },
  ],
  courses: [
    {
      id: 'sh-c1',
      title: 'Vedic Astrology & Planetary Dasha Mastery',
      description: 'The complete masterclass on chart reading, planetary conjunctions, and calculating timing of key life events.',
      difficulty: 'All Levels',
      duration: '12 Weeks',
      format: 'Live Online',
      hasCertificate: true,
      instructor: 'Shaunak S. Patthak',
      image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80',
      badge: 'Best Seller',
      price: '₹15,999',
    },
    {
      id: 'sh-c2',
      title: 'Astro-Vastu Spatial Synthesis',
      description: 'Bridge birth chart planetary placements with 16 Vastu directional zones to neutralize negative horoscope transits.',
      difficulty: 'Advanced',
      duration: '8 Weeks',
      format: 'Hybrid Masterclass',
      hasCertificate: true,
      instructor: 'Shaunak S. Patthak',
      image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
      badge: 'Advanced',
      price: '₹19,500',
    },
    {
      id: 'sh-c3',
      title: 'Scientific Gemology & Mantra Science',
      description: 'Authentic prescription of natural gemstones, metals, and sound vibrations to strengthen auspicious planetary forces.',
      difficulty: 'Intermediate',
      duration: '4 Weeks',
      format: 'Self-Paced Video',
      hasCertificate: true,
      instructor: 'Shaunak S. Patthak',
      image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80',
      badge: 'Most Popular',
      price: '₹7,999',
    },
    {
      id: 'sh-c4',
      title: 'Muhurta & Auspicious Timing Selection',
      description: 'Master time-election science for marriage, business launch, house warming, and strategic investment dates.',
      difficulty: 'Beginner',
      duration: '3 Weeks',
      format: 'Live Online',
      hasCertificate: true,
      instructor: 'Shaunak S. Patthak',
      image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
      badge: 'New',
      price: '₹5,499',
    },
  ],
  testimonials: [
    {
      id: 'sht1',
      name: 'Dr. Sunita Deshmukh',
      role: 'Medical Practitioner, Bengaluru',
      rating: 5,
      content: 'Shaunak S. Patthak’s Astro-Vastu course transformed my understanding of medical astrology and spatial energy completely.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Vedic Astrology & Planetary Dasha',
    },
    {
      id: 'sht2',
      name: 'Vikramaditya Roy',
      role: 'Investment Banker, Singapore',
      rating: 5,
      content: 'The Dasha timing calculations taught by Shaunak S. Patthak helped me time key financial moves with uncanny accuracy.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Astro-Vastu Spatial Synthesis',
    },
    {
      id: 'sht3',
      name: 'Meera Kulkarni',
      role: 'Astrology Consultant, Delhi',
      rating: 5,
      content: 'The gemstone prescription module cleared years of confusion. Shaunak S. Patthak is a true ocean of Vedic knowledge.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      courseTitle: 'Scientific Gemology & Mantra',
    },
  ],
  faqs: [
    {
      id: 'shf1',
      question: 'Is horoscope chart reading taught from basic levels?',
      answer: 'Yes! Shaunak S. Patthak starts with foundational concepts like planets, zodiac signs, and houses before advancing to complex Dashas.',
    },
    {
      id: 'shf2',
      question: 'How does Astro-Vastu differ from standard Vastu?',
      answer: 'Standard Vastu treats every house identically, whereas Astro-Vastu customizes remedies based on the unique horoscope of the property owner.',
    },
    {
      id: 'shf3',
      question: 'Will I be able to analyze charts independently after completion?',
      answer: 'Yes, students receive hands-on chart practice sessions and an accredited certificate certifying their competence as an Astro-Vastu practitioner.',
    },
  ],
  events: [
    {
      id: 'she1',
      date: 'Oct 28, 2026',
      time: '8:00 PM IST',
      speaker: 'Shaunak S. Patthak',
      topic: 'Unlocking Saturn & Rahu Transits for Wealth & Career',
      seatsAvailable: 20,
      totalSeats: 120,
      countdownTarget: '2026-10-28T20:00:00',
    },
    {
      id: 'she2',
      date: 'Nov 15, 2026',
      time: '6:30 PM IST',
      speaker: 'Shaunak S. Patthak',
      topic: 'Astro-Vastu Remedial Overlays Masterclass',
      seatsAvailable: 15,
      totalSeats: 90,
      countdownTarget: '2026-11-15T18:30:00',
    },
  ],
  freeResources: [
    {
      id: 'shr1',
      title: 'Vedic Chart Reading Guide & House Handbook',
      type: 'eBook',
      description: 'A essential reference PDF mapping the 12 astrology houses and planetary lordships.',
      downloadUrl: '#',
      image: '/gemstone-assets/blue-sapphire.jpg',
    },
    {
      id: 'shr2',
      title: 'Planetary Gemstones & Metal Compatibility Chart',
      type: 'Cheat Sheet',
      description: 'A quick guide to verifying authentic natural gemstone substitutes and metals.',
      downloadUrl: '#',
      image: '/gemstone-assets/cats-eye.jpg',
    },
  ],
  contactDetails: {
    phone: '+91 99537 13176',
    whatsapp: 'https://wa.me/919953713176',
    email: 'support@shaunakpatthak.com',
    address: 'Ahmedabad, Gujarat & Delhi, India',
  },
  socialLinks: {
    youtube: 'https://youtube.com/@shaunakpatthak',
    facebook: 'https://facebook.com/shaunakpatthak',
    instagram: 'https://instagram.com/shaunakpatthak',
  },
};
