import { Course } from './types';

export const COURSES: Course[] = [
  {
    id: "c1",
    name: "Complete Chaldean Numerology",
    description: "The definitive masterclass on Chaldean grid calculations. Uncover planetary compound frequencies, name numbers, and birth destiny grids.",
    thumbnail: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80",
    duration: "12 Weeks",
    level: "All Levels",
    category: "Chaldean Science",
    instructor: "Raajeev Singh Chauhann",
    price: "₹14,999",
    discount: "10%",
    certificate: true,
    featured: true,
    seoUrl: "/academy/complete-chaldean-numerology",
    cmsId: "course-chaldean-01"
  },
  {
    id: "c2",
    name: "Mobile Numerology Masterclass",
    description: "Transform your most frequent digital companion into an active wealth and communication magnet. Master the science of combination frequencies.",
    thumbnail: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Frequency Science",
    instructor: "Raajeev Singh Chauhann",
    price: "₹5,999",
    discount: "15%",
    certificate: true,
    featured: true,
    seoUrl: "/academy/mobile-numerology",
    cmsId: "course-mobile-01"
  },
  {
    id: "c3",
    name: "Premium Name Numerology",
    description: "Master the art and science of signature spellings, branding, and trademark correction using advanced Chaldean vibrations.",
    thumbnail: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
    duration: "6 Weeks",
    level: "Advanced",
    category: "Signature Correction",
    instructor: "Raajeev Singh Chauhann",
    price: "₹9,999",
    discount: "0%",
    certificate: true,
    featured: true,
    seoUrl: "/academy/premium-name-numerology",
    cmsId: "course-name-01"
  },
  {
    id: "c4",
    name: "Lo Shu Grid Mastery",
    description: "Learn Chinese Numerology paradigms combined with Indian Vedic placements to map the nine key aspects of human consciousness.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    duration: "3 Weeks",
    level: "Beginner",
    category: "Lo Shu Grid",
    instructor: "Raajeev Singh Chauhann",
    price: "₹4,499",
    discount: "0%",
    certificate: true,
    featured: false,
    seoUrl: "/academy/lo-shu-grid-mastery",
    cmsId: "course-loshu-01"
  },
  {
    id: "c5",
    name: "Business Numerology Strategy",
    description: "Designed exclusively for entrepreneurs. Select powerful trade names, partner shares, and incorporation dates for continuous expansion.",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
    duration: "8 Weeks",
    level: "Advanced",
    category: "Business Mastery",
    instructor: "Raajeev Singh Chauhann",
    price: "₹18,500",
    discount: "20%",
    certificate: true,
    featured: true,
    seoUrl: "/academy/business-numerology",
    cmsId: "course-business-01"
  },
  {
    id: "c6",
    name: "Vastu Shastra Foundation",
    description: "Understand the architectural elements, directions, and planetary nodes governing physical buildings without demolition.",
    thumbnail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
    duration: "10 Weeks",
    level: "All Levels",
    category: "Vastu Shastra",
    instructor: "Raajeev Singh Chauhann",
    price: "₹16,200",
    discount: "10%",
    certificate: true,
    featured: true,
    seoUrl: "/academy/vastu-foundation",
    cmsId: "course-vastu-01"
  },
  {
    id: "c7",
    name: "Astrology Essentials & Dashas",
    description: "Unpack the 12 houses of the natal chart, main planetary cycles (Dashas), and standard remedial gemstone configurations.",
    thumbnail: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80",
    duration: "8 Weeks",
    level: "Intermediate",
    category: "Vedic Astrology",
    instructor: "Raajeev Singh Chauhann",
    price: "₹11,500",
    discount: "0%",
    certificate: true,
    featured: false,
    seoUrl: "/academy/astrology-essentials",
    cmsId: "course-astrology-01"
  },
  {
    id: "c8",
    name: "Meditation & Spiritual Awakening",
    description: "Raise your core pranic energy, stabilize the nervous system, and conquer subconscious panic through authentic Vedic techniques.",
    thumbnail: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
    duration: "4 Weeks",
    level: "Beginner",
    category: "Sadhana & Meditation",
    instructor: "Raajeev Singh Chauhann",
    price: "₹3,500",
    discount: "0%",
    certificate: false,
    featured: false,
    seoUrl: "/academy/meditation-spiritual",
    cmsId: "course-meditation-01"
  }
];
