import { Social } from './types';
import { Assets } from './assets';

export const SOCIAL_REGISTRY: Social[] = [
  {
    id: "sc_yt_main",
    platform: "YouTube",
    displayName: "LEO Family Occult Gyan",
    description: "Official educational hub for Astro-Numerology, Vastu Science, and Occult Remedies.",
    category: "Education",
    url: "https://youtube.com/@leofamilyoccultgyan",
    username: "@leofamilyoccultgyan",
    thumbnail: "/gemstone-assets/logo.jpg",
    banner: "/gemstone-assets/background.png",
    logo: "Youtube",
    brandColor: "#FF0000",
    hoverColor: "#CC0000",
    previewImage: "https://i.ytimg.com/vi/RcmLxAECJAc/maxresdefault.jpg",
    openGraphImage: "/gemstone-assets/logo.jpg",
    verified: true,
    followers: "120K+ Seekers",
    subscribers: "120K+",
    videos: "340+",
    createdDate: "2018-05-12",
    status: "Active",
    displayPriority: 1,
    featured: true,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "/api/social/youtube/main",
    futureAnalytics: ""
  },
  {
    id: "sc_yt_founder",
    platform: "YouTube",
    displayName: "Raajeev Singh Chauhann",
    description: "Deep spiritual mentorship, motivational guidance, and ancient wisdom masterclasses.",
    category: "Mentorship",
    url: "https://youtube.com/@raajeevsinghchauhann",
    username: "@raajeevsinghchauhann",
    thumbnail: Assets.founder.image,
    banner: Assets.founder.image,
    logo: "Youtube",
    brandColor: "#FF0000",
    hoverColor: "#CC0000",
    previewImage: "https://i.ytimg.com/vi/RcmLxAECJAc/maxresdefault.jpg",
    openGraphImage: Assets.founder.image,
    verified: true,
    followers: "80K+ Seekers",
    subscribers: "80K+",
    videos: "210+",
    createdDate: "2019-11-20",
    status: "Active",
    displayPriority: 2,
    featured: true,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "/api/social/youtube/founder",
    futureAnalytics: ""
  },
  {
    id: "sc_yt_films",
    platform: "YouTube",
    displayName: "LEO Family Indian Films",
    description: "Blending cinema and spirituality. Inspiring web series, lifestyle segments, and short movies.",
    category: "Entertainment",
    url: "https://youtube.com/@leofamilyindianfilms",
    username: "@leofamilyindianfilms",
    thumbnail: "/gemstone-assets/logo.jpg",
    banner: "/gemstone-assets/background.png",
    logo: "Youtube",
    brandColor: "#FF0000",
    hoverColor: "#CC0000",
    previewImage: "/gemstone-assets/background.png",
    openGraphImage: "/gemstone-assets/logo.jpg",
    verified: false,
    followers: "150K+ Subscribers",
    subscribers: "150K+",
    videos: "90+",
    createdDate: "2020-03-15",
    status: "Active",
    displayPriority: 3,
    featured: true,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "/api/social/youtube/films",
    futureAnalytics: ""
  },
  {
    id: "sc_fb",
    platform: "Facebook",
    displayName: "Raajeev Singh Chauhann",
    description: "Direct community interactions, daily calculation posts, and global remedial discussion.",
    category: "Community",
    url: "https://facebook.com/RaajeevSinghChauhann",
    username: "Raajeev Singh Chauhann",
    thumbnail: Assets.founder.image,
    banner: "/gemstone-assets/background.png",
    logo: "Facebook",
    brandColor: "#1877F2",
    hoverColor: "#165EBF",
    previewImage: "/gemstone-assets/background.png",
    openGraphImage: Assets.founder.image,
    verified: true,
    followers: "65K+",
    subscribers: "65K+",
    videos: "",
    createdDate: "2015-08-20",
    status: "Active",
    displayPriority: 4,
    featured: true,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "/api/social/facebook",
    futureAnalytics: ""
  },
  {
    id: "sc_ig",
    platform: "Instagram",
    displayName: "LEO Family Official",
    description: "Daily numerology insights, gemstone alignment cards, and spiritual wisdom shorts.",
    category: "Visuals",
    url: "https://instagram.com",
    username: "leofamily.official",
    thumbnail: "/gemstone-assets/logo.jpg",
    banner: "/gemstone-assets/background.png",
    logo: "Instagram",
    brandColor: "#E1306C",
    hoverColor: "#C13584",
    previewImage: "/gemstone-assets/logo.jpg",
    openGraphImage: "/gemstone-assets/logo.jpg",
    verified: false,
    followers: "Coming Soon",
    subscribers: "Coming Soon",
    videos: "",
    createdDate: "",
    status: "Planned",
    displayPriority: 5,
    featured: false,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "",
    futureAnalytics: ""
  },
  {
    id: "sc_ln",
    platform: "LinkedIn",
    displayName: "LEO Family Corporate",
    description: "Corporate spatial energetics, organizational numerology alignments, and leadership coaching.",
    category: "Professional",
    url: "https://linkedin.com",
    username: "leofamily",
    thumbnail: "/gemstone-assets/logo.jpg",
    banner: "/gemstone-assets/background.png",
    logo: "Linkedin",
    brandColor: "#0A66C2",
    hoverColor: "#004182",
    previewImage: "/gemstone-assets/logo.jpg",
    openGraphImage: "/gemstone-assets/logo.jpg",
    verified: false,
    followers: "Coming Soon",
    subscribers: "Coming Soon",
    videos: "",
    createdDate: "",
    status: "Planned",
    displayPriority: 6,
    featured: false,
    visible: true,
    openInNewTab: true,
    futureApiEndpoint: "",
    futureAnalytics: ""
  }
];

export const SOCIAL_INFO = {
  youtube: {
    main: "https://youtube.com/@leofamilyoccultgyan",
    founder: "https://youtube.com/@raajeevsinghchauhann",
    films: "https://youtube.com/@leofamilyindianfilms"
  },
  facebook: "https://facebook.com/RaajeevSinghChauhann",
  
  previews: {
    youtube: {
      main: {
        title: "LEO Family Occult Gyan",
        subscribers: "120K+ Seekers",
        avatar: "/gemstone-assets/logo.jpg",
        banner: "/gemstone-assets/background.png",
        description: "Official educational hub for Astro-Numerology, Vastu Science, and Occult Remedies."
      },
      founder: {
        title: "Raajeev Singh Chauhann Official",
        subscribers: "80K+ Followers",
        avatar: Assets.founder.image,
        banner: Assets.founder.image,
        description: "Deep spiritual mentorship, motivational guidance, and ancient wisdom masterclasses."
      },
      films: {
        title: "LEO Family Indian Films",
        subscribers: "150K+ Subscribers",
        avatar: "/gemstone-assets/logo.jpg",
        banner: "/gemstone-assets/background.png",
        description: "Blending cinema and spirituality. Inspiring web series, lifestyle segments, and short movies."
      }
    },
    facebook: {
      title: "Raajeev Singh Chauhann Community",
      followers: "65K+ Members",
      avatar: Assets.founder.image,
      banner: "/gemstone-assets/background.png",
      description: "Direct community interactions, daily calculation posts, and global remedial discussion."
    }
  }
};
