import React from 'react';
import { motion } from 'framer-motion';
import { 
  Heart, 
  X, 
  Sparkles, 
  CheckCircle2, 
  AlertTriangle, 
  Zap, 
  Printer, 
  Share2, 
  Grid3X3,
  Flame,
  Award
} from 'lucide-react';
import { CompatibilityResult, Language } from '../../utils/numerologyEngine';

interface CompatibilityReportViewProps {
  result: CompatibilityResult;
  lang: Language;
  onClose: () => void;
}

export default function CompatibilityReportView({
  result,
  lang,
  onClose
}: CompatibilityReportViewProps) {

  const handlePrint = () => {
    window.print();
  };

  const handleShare = (platform: 'whatsapp' | 'email') => {
    const text = `Check out our Lo Shu Grid Relationship Compatibility analysis! Match Score: ${result.score}%. Generated by Leo Family.`;
    const url = window.location.href;
    let shareUrl = '';

    if (platform === 'whatsapp') {
      shareUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(text + ' ' + url)}`;
    } else {
      shareUrl = `mailto:?subject=Our Compatibility Report&body=${encodeURIComponent(text + '\n\nRead here: ' + url)}`;
    }

    window.open(shareUrl, '_blank');
  };

  const t = {
    en: {
      title: "Relationship Compatibility Report",
      subtitle: "Side-by-side cosmic energy comparison using Lo Shu Numerology",
      matchScore: "Match Synergy Score",
      verdict: "Compatibility Verdict",
      grids: "Side-by-Side Lo Shu Grids",
      synergy: "Core Synergy Points",
      challenges: "Relationship Challenges",
      remedies: "Harmonizing Remedies",
      print: "Print / PDF Report",
      close: "Close Analysis",
      disclaimer: "Disclaimer: This comparison is based on traditional Lo Shu grid calculations to highlight mutual compatibility trends. Successful relationships rely on communication, trust, and efforts from both partners.",
      driver: "Driver / Psychic",
      conductor: "Conductor / Destiny"
    },
    hi: {
      title: "संबंध अनुकूलता रिपोर्ट",
      subtitle: "लो शू अंकशास्त्र का उपयोग करके ऊर्जा तुलना",
      matchScore: "अनुकूलता तालमेल स्कोर",
      verdict: "संगतता निर्णय",
      grids: "आमने-सामने लो शू ग्रिड",
      synergy: "मुख्य सकारात्मक तालमेल बिंदु",
      challenges: "संबंधों की चुनौतियाँ",
      remedies: "सामंजस्यपूर्ण उपाय",
      print: "प्रिंट / PDF रिपोर्ट",
      close: "विश्लेषण बंद करें",
      disclaimer: "अस्वीकरण: यह तुलना आपसी अनुकूलता प्रवृत्तियों को उजागर करने के लिए पारंपरिक गणनाओं पर आधारित है। सफल रिश्ते विश्वास और दोनों भागीदारों के प्रयासों पर निर्भर करते हैं।",
      driver: "ड्राइवर / मूलांक",
      conductor: "कंडक्टर / भाग्यांक"
    },
    gu: {
      title: "લગ્ન - ભાગીદારી સુમેળ રિપોર્ટ",
      subtitle: "લો શૂ અંકશાસ્ત્ર આધારીત પરસ્પર ઉર્જા સરખામણી",
      matchScore: "પરસ્પર સુમેળ સ્કોર",
      verdict: "સુમેળ નિર્ણય",
      grids: "સામસામે લો શૂ ગ્રીડ",
      synergy: "મુખ્ય હકારાત્મક સુમેળ બિંદુઓ",
      challenges: "પરસ્પર પડકારો",
      remedies: "સુમેળ વધારવાના ઉપાયો",
      print: "પ્રિન્ટ / PDF રિપોર્ટ",
      close: "રિપોર્ટ બંધ કરો",
      disclaimer: "અસ્વીકરણ: આ સરખામણી પરસ્પર સુમેળની સંભાવના દર્શાવવા માટે છે. સફળ સંબંધો પરસ્પર વિશ્વાસ અને બંને ભાગીદારોના પ્રયાસો પર આધાર રાખે છે.",
      driver: "ડ્રાઈવર / મૂલાંક",
      conductor: "કંડક્ટર / ભાગ્યાંક"
    }
  }[lang];

  const gridNumbers = [
    [4, 9, 2],
    [3, 5, 7],
    [8, 1, 6]
  ];

  return (
    <div className="space-y-12 print:space-y-6">
      <style>{`
        @media print {
          .no-print { display: none !important; }
          .print-card { border: 1px solid #d4af37 !important; background: white !important; box-shadow: none !important; page-break-inside: avoid; }
        }
      `}</style>

      {/* 👑 COMPATIBILITY HEADER BANNER */}
      <div className="bg-gradient-to-br from-amber-50/70 via-[#FAF9F6] to-white p-8 lg:p-12 rounded-3xl border-2 border-amber-300/30 text-center relative overflow-hidden shadow-xl print-card">
        {/* Shimmer rings */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 border border-amber-300/10 rounded-full pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[420px] h-[420px] border border-amber-300/5 rounded-full pointer-events-none" />

        <div className="max-w-3xl mx-auto space-y-6">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-700 text-xs font-bold uppercase tracking-[0.3em] rounded-full border border-rose-100">
            <Heart className="w-4 h-4 fill-rose-500 text-rose-500 animate-pulse" />
            LEO FAMILY LOVE COMPATIBILITY
          </div>

          <h2 className="text-3xl lg:text-5xl font-cinzel font-bold text-amber-600 uppercase tracking-widest">
            {t.title}
          </h2>
          <p className="text-zinc-500 font-light italic text-sm lg:text-lg">
            {t.subtitle}
          </p>

          <div className="h-[2px] bg-gradient-to-r from-transparent via-amber-400 to-transparent w-full my-6" />

          {/* SIDE-BY-SIDE NAMES & RADIAL PROGRESS CHART */}
          <div className="flex flex-col md:flex-row items-center justify-around gap-8 py-4">
            <div className="text-center md:text-right space-y-2">
              <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider">Partner 1</span>
              <h3 className="text-2xl font-serif font-bold text-zinc-800 capitalize tracking-wide">{result.partner1.name}</h3>
              <p className="font-mono text-sm text-zinc-500">{result.partner1.dob}</p>
              <div className="flex items-center gap-2 justify-center md:justify-end text-xs">
                <span className="text-zinc-500">{t.driver}: <strong className="text-zinc-800">{result.partner1.driver}</strong></span>
                <span className="text-zinc-300">|</span>
                <span className="text-zinc-500">{t.conductor}: <strong className="text-zinc-800">{result.partner1.conductor}</strong></span>
              </div>
            </div>

            {/* Radial Match Synergy Score Chart */}
            <div className="relative w-36 h-36 flex items-center justify-center bg-white rounded-full shadow-lg border border-amber-100">
              {/* Progress Circle SVG */}
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                <circle 
                  cx="50" cy="50" r="42" 
                  fill="transparent" 
                  stroke="#FAF9F6" 
                  strokeWidth="8" 
                />
                <circle 
                  cx="50" cy="50" r="42" 
                  fill="transparent" 
                  stroke="url(#goldGradient)" 
                  strokeWidth="8" 
                  strokeDasharray={`${2 * Math.PI * 42}`}
                  strokeDashoffset={`${2 * Math.PI * 42 * (1 - result.score / 100)}`}
                  strokeLinecap="round"
                />
                <defs>
                  <linearGradient id="goldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stopColor="#fbbf24" />
                    <stop offset="100%" stopColor="#d97706" />
                  </linearGradient>
                </defs>
              </svg>
              <div className="absolute text-center">
                <span className="text-3xl font-cinzel font-bold text-amber-600 gold-glow-text">{result.score}%</span>
                <span className="text-[9px] uppercase font-bold text-zinc-400 block tracking-wider">Synergy</span>
              </div>
            </div>

            <div className="text-center md:text-left space-y-2">
              <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider">Partner 2</span>
              <h3 className="text-2xl font-serif font-bold text-zinc-800 capitalize tracking-wide">{result.partner2.name}</h3>
              <p className="font-mono text-sm text-zinc-500">{result.partner2.dob}</p>
              <div className="flex items-center gap-2 justify-center md:justify-start text-xs">
                <span className="text-zinc-500">{t.driver}: <strong className="text-zinc-800">{result.partner2.driver}</strong></span>
                <span className="text-zinc-300">|</span>
                <span className="text-zinc-500">{t.conductor}: <strong className="text-zinc-800">{result.partner2.conductor}</strong></span>
              </div>
            </div>
          </div>

          <div className="bg-white/50 p-4 rounded-2xl border border-amber-200/40 inline-flex items-center gap-2 max-w-md mx-auto">
            <Award className="w-5 h-5 text-amber-600 shrink-0" />
            <div className="text-left">
              <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider">{t.verdict}</span>
              <p className="text-xs font-bold text-amber-700 uppercase tracking-widest">{result.verdict}</p>
            </div>
          </div>
        </div>
      </div>

      {/* 🎛️ ACTION BAR */}
      <div className="no-print bg-white/90 backdrop-blur-md p-4 rounded-2xl border border-amber-100 shadow-md flex justify-between items-center">
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-5 py-2.5 bg-amber-500 hover:bg-amber-600 text-white font-bold text-xs uppercase tracking-wider rounded-xl transition-all shadow-md"
        >
          <Printer className="w-4 h-4" />
          {t.print}
        </button>

        <div className="flex items-center gap-2">
          <button 
            onClick={() => handleShare('whatsapp')}
            className="p-2 hover:bg-emerald-50 text-emerald-600 rounded-full transition-all"
            title="Share on WhatsApp"
          >
            <Share2 className="w-4 h-4" />
          </button>
          <button
            onClick={onClose}
            className="p-2 hover:bg-rose-50 text-rose-500 rounded-full transition-all border border-rose-100 ml-2"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* 🔮 DETAILED GRIDS COMPARISON & ANALYSIS */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Partner 1 Lo Shu Grid */}
        <div className="bg-white p-6 rounded-3xl border border-amber-300/10 shadow-md print-card">
          <h4 className="text-sm font-cinzel font-bold text-amber-700 uppercase tracking-wider mb-6 text-center">
            {result.partner1.name}'s Lo Shu Grid
          </h4>
          <div className="max-w-[280px] mx-auto">
            <div className="grid grid-cols-3 gap-2 bg-zinc-50 p-3 rounded-2xl border border-zinc-100">
              {gridNumbers.map((row, rI) => (
                row.map((num, cI) => {
                  const count = result.partner1.grid[num] || 0;
                  const display = count > 0 ? num.toString().repeat(count) : '';
                  return (
                    <div 
                      key={`${rI}-${cI}`}
                      className={`aspect-square rounded-xl flex items-center justify-center relative font-serif text-lg font-bold border ${
                        count > 0 
                          ? 'bg-amber-500 text-white border-amber-600 shadow-md' 
                          : 'bg-white text-zinc-100 border-zinc-100'
                      }`}
                    >
                      <span className="absolute top-1 left-2 text-[8px] font-mono opacity-25">{num}</span>
                      {display || num}
                    </div>
                  );
                })
              ))}
            </div>
          </div>
        </div>

        {/* Partner 2 Lo Shu Grid */}
        <div className="bg-white p-6 rounded-3xl border border-amber-300/10 shadow-md print-card">
          <h4 className="text-sm font-cinzel font-bold text-amber-700 uppercase tracking-wider mb-6 text-center">
            {result.partner2.name}'s Lo Shu Grid
          </h4>
          <div className="max-w-[280px] mx-auto">
            <div className="grid grid-cols-3 gap-2 bg-zinc-50 p-3 rounded-2xl border border-zinc-100">
              {gridNumbers.map((row, rI) => (
                row.map((num, cI) => {
                  const count = result.partner2.grid[num] || 0;
                  const display = count > 0 ? num.toString().repeat(count) : '';
                  return (
                    <div 
                      key={`${rI}-${cI}`}
                      className={`aspect-square rounded-xl flex items-center justify-center relative font-serif text-lg font-bold border ${
                        count > 0 
                          ? 'bg-amber-500 text-white border-amber-600 shadow-md' 
                          : 'bg-white text-zinc-100 border-zinc-100'
                      }`}
                    >
                      <span className="absolute top-1 left-2 text-[8px] font-mono opacity-25">{num}</span>
                      {display || num}
                    </div>
                  );
                })
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* DEEP COMPATIBILITY ANALYSIS NARRATIVE */}
      <div className="bg-[#FAF9F6] p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
        <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-4">
          Deep Cosmic Alignment Interpretation
        </h3>
        <p className="text-xs text-zinc-700 leading-relaxed font-light font-serif italic">
          {result.analysis}
        </p>
      </div>

      {/* SYNERGIES, CHALLENGES & SHARED REMEDIES BENTO CONTAINER */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* Synergy points */}
        <div className="bg-white p-6 rounded-3xl border border-emerald-100 shadow-sm print-card">
          <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-800 flex items-center gap-1.5 mb-4">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            {t.synergy}
          </h4>
          <ul className="space-y-3">
            {result.synergyPoints.map((pt, i) => (
              <li key={i} className="text-xs text-zinc-600 leading-relaxed font-light">
                {pt}
              </li>
            ))}
          </ul>
        </div>

        {/* Challenges points */}
        <div className="bg-white p-6 rounded-3xl border border-rose-100 shadow-sm print-card">
          <h4 className="text-xs font-bold uppercase tracking-wider text-rose-800 flex items-center gap-1.5 mb-4">
            <AlertTriangle className="w-4 h-4 text-rose-500" />
            {t.challenges}
          </h4>
          <ul className="space-y-3">
            {result.challenges.map((ch, i) => (
              <li key={i} className="text-xs text-zinc-600 leading-relaxed font-light">
                {ch}
              </li>
            ))}
          </ul>
        </div>

        {/* Harmonizing remedies */}
        <div className="bg-gradient-to-br from-amber-50/50 to-white p-6 rounded-3xl border border-amber-200/50 shadow-sm print-card">
          <h4 className="text-xs font-bold uppercase tracking-wider text-amber-800 flex items-center gap-1.5 mb-4">
            <Zap className="w-4 h-4 text-amber-500" />
            {t.remedies}
          </h4>
          <ul className="space-y-3">
            {result.remedies.map((rem, i) => (
              <li key={i} className="text-xs text-zinc-700 leading-relaxed font-medium italic">
                "{rem}"
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* DISCLAIMER */}
      <div className="pt-8 border-t border-zinc-200 text-[10px] text-zinc-400 leading-relaxed italic text-center print-card">
        {t.disclaimer}
      </div>
    </div>
  );
}
