import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Calendar, 
  User, 
  Info, 
  Sparkles, 
  Star, 
  Grid3X3, 
  Download, 
  Printer, 
  Share2, 
  Heart, 
  Activity, 
  Compass, 
  DollarSign, 
  Briefcase, 
  ShieldAlert, 
  Languages, 
  Award, 
  ArrowRight, 
  Lock, 
  Scale, 
  BookOpen, 
  Sparkle, 
  Flame, 
  CircleDot, 
  Zap, 
  TrendingUp, 
  X,
  CompassIcon,
  Eye,
  Bookmark
} from 'lucide-react';
import { NumerologyReport, Language } from '../../utils/numerologyEngine';

interface PremiumReportViewProps {
  report: NumerologyReport;
  lang: Language;
  setLang: (lang: Language) => void;
  onClose: () => void;
  userName: string;
  onSave?: () => void;
}

export default function PremiumReportView({
  report,
  lang,
  setLang,
  onClose,
  userName,
  onSave
}: PremiumReportViewProps) {
  const [activeThemeTab, setActiveThemeTab] = useState<'dashboard' | 'personality' | 'lifestyle' | 'remedies' | 'all'>('dashboard');
  const [hoveredNumber, setHoveredNumber] = useState<number | null>(null);
  const [isSaved, setIsSaved] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  const handleSaveLocally = () => {
    const savedReports = JSON.parse(localStorage.getItem('numerology_reports') || '[]');
    const newReport = {
      id: Date.now().toString(),
      name: userName || 'Anonymous',
      dob: report.personalInfo.dob,
      timestamp: new Date().toLocaleDateString(),
      reportData: report
    };
    
    // Check if already exists
    const exists = savedReports.some((r: any) => r.dob === report.personalInfo.dob && r.name === userName);
    if (!exists) {
      savedReports.push(newReport);
      localStorage.setItem('numerology_reports', JSON.stringify(savedReports));
    }
    
    setIsSaved(true);
    if (onSave) {
      onSave();
    }
    setTimeout(() => setIsSaved(false), 3000);
  };

  const handleShare = (platform: 'whatsapp' | 'email' | 'facebook' | 'x') => {
    const text = `Check out my Premium Lo Shu Grid Numerology Report! My Destiny Number is ${report.personalInfo.conductor} and Psychic is ${report.personalInfo.driver}. Generated by Leo Family.`;
    const url = window.location.href;
    let shareUrl = '';

    switch (platform) {
      case 'whatsapp':
        shareUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(text + ' ' + url)}`;
        break;
      case 'email':
        shareUrl = `mailto:?subject=My Numerology Report&body=${encodeURIComponent(text + '\n\nRead here: ' + url)}`;
        break;
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
        break;
      case 'x':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
        break;
    }

    window.open(shareUrl, '_blank');
  };

  // Translations
  const t = {
    en: {
      reportTitle: "Premium Lo Shu Grid Report",
      subtitle: "The divine blueprint of your life & cosmic energy pattern",
      psychic: "Psychic / Driver",
      destiny: "Destiny / Conductor",
      lifePath: "Life Path",
      personalYear: "Personal Year",
      personalMonth: "Personal Month",
      birthElement: "Birth Year Element",
      yinYang: "Yin / Yang Energy",
      score: "Overall Life Harmony",
      downloadPdf: "Print / PDF Report",
      saveReport: "Save Report",
      saved: "Saved!",
      share: "Share Report",
      language: "Language",
      close: "Close Report",
      loShuTitle: "Interactive Lo Shu Grid",
      hoverTip: "Hover over cells to highlight energy profiles & missing areas.",
      tabs: {
        dashboard: "Summary & Grid",
        personality: "Personality & Wealth",
        lifestyle: "Health & Career",
        remedies: "Remedies & Forecast",
        all: "View Full Report"
      },
      disclaimer: "Disclaimer: This numerological report is intended for self-reflection and personal guidance. Predictions are tendencies rather than absolute certainties. Consult medical professionals for health diagnoses.",
      strengths: "Core Strengths",
      weaknesses: "Development Areas",
      hiddenTalents: "Hidden Talents",
      innerNature: "Inner Nature",
      outerPersonality: "Outer Personality",
      wealthRating: "Wealth Attraction",
      marriageCompat: "Relationship Compatibility",
      suggestions: "Lifestyle Recommendations",
      challenges: "Life Challenges & Blocks",
      lucky: "Auspicious Factors",
      unlucky: "Cautionary Factors",
      remediesTitle: "Cosmic Balance Remedies",
      forecastTitle: "Annual Life Cycle Forecast",
      personalitySummary: "Overall Personality Synthesis",
      careerSuitability: "Career Field Suitability",
      gridExplanation: "The Lo Shu Grid is an ancient 3x3 magic square. The numbers present in your birth date are placed in their respective squares, while the missing ones reveal lessons to be mastered."
    },
    hi: {
      reportTitle: "प्रीमियम लो शू ग्रिड रिपोर्ट",
      subtitle: "आपके जीवन का दिव्य खाका और ब्रह्मांडीय ऊर्जा पैटर्न",
      psychic: "ड्राइवर / मूलांक",
      destiny: "कंडक्टर / भाग्यांक",
      lifePath: "जीवन पथ संख्या",
      personalYear: "व्यक्तिगत वर्ष",
      personalMonth: "व्यक्तिगत महीना",
      birthElement: "जन्म वर्ष तत्व",
      yinYang: "यिन / यांग संतुलन",
      score: "समग्र जीवन सामंजस्य",
      downloadPdf: "प्रिंट / PDF रिपोर्ट",
      saveReport: "रिपोर्ट सहेजें",
      saved: "सहेजा गया!",
      share: "रिपोर्ट साझा करें",
      language: "भाषा",
      close: "रिपोर्ट बंद करें",
      loShuTitle: "इंटरैक्टिव लो शू ग्रिड",
      hoverTip: "ऊर्जा प्रोफाइल और लुप्त क्षेत्रों को हाइलाइट करने के लिए सेल पर होवर करें।",
      tabs: {
        dashboard: "सारांश और ग्रिड",
        personality: "व्यक्तित्व और धन",
        lifestyle: "स्वास्थ्य और करियर",
        remedies: "उपाय और भविष्य",
        all: "पूर्ण रिपोर्ट देखें"
      },
      disclaimer: "अस्वीकरण: यह अंकशास्त्र रिपोर्ट आत्म-चिंतन और व्यक्तिगत मार्गदर्शन के लिए है। भविष्यवाणियां निश्चितताओं के बजाय प्रवृत्तियों को दर्शाती हैं।",
      strengths: "मुख्य ताकत",
      weaknesses: "सुधार के क्षेत्र",
      hiddenTalents: "छिपी हुई प्रतिभाएं",
      innerNature: "आंतरिक स्वभाव",
      outerPersonality: "बाहरी व्यक्तित्व",
      wealthRating: "धन आकर्षण रेटिंग",
      marriageCompat: "संबंध अनुकूलता स्तर",
      suggestions: "जीवनशैली सुझाव",
      challenges: "जीवन की चुनौतियाँ और बाधाएं",
      lucky: "शुभ कारक",
      unlucky: "सावधानी वाले कारक",
      remediesTitle: "ऊर्जा संतुलन के उपाय",
      forecastTitle: "वार्षिक चक्र पूर्वानुमान",
      personalitySummary: "समग्र व्यक्तित्व संश्लेषण",
      careerSuitability: "करियर क्षेत्र उपयुक्तता",
      gridExplanation: "लो शू ग्रिड एक प्राचीन 3x3 मैजिक स्क्वायर है। आपकी जन्म तिथि में मौजूद नंबरों को उनके संबंधित स्थानों पर रखा जाता है, जबकि लुप्त नंबर जीवन पाठ दर्शाते हैं।"
    },
    gu: {
      reportTitle: "પ્રીમિયમ લો શૂ ગ્રીડ રિપોર્ટ",
      subtitle: "તમારા જીવનનો દૈવી નકશો અને બ્રહ્માંડિય ઉર્જા પેટર્ન",
      psychic: "ડ્રાઈવર / મૂલાંક",
      destiny: "કંડક્ટર / ભાગ્યાંક",
      lifePath: "જીવન પથ સંખ્યા",
      personalYear: "વ્યક્તિગત વર્ષ",
      personalMonth: "વ્યક્તિગત મહિનો",
      birthElement: "જન્મ વર્ષ તત્વ",
      yinYang: "યિન / યાંગ સંતુલન",
      score: "સમગ્ર જીવન સુમેળ",
      downloadPdf: "પ્રિન્ટ / PDF રિપોર્ટ",
      saveReport: "રિપોર્ટ સાચવો",
      saved: "સાચવેલ!",
      share: "રિપોર્ટ શેર કરો",
      language: "ભાષા",
      close: "રિપોર્ટ બંધ કરો",
      loShuTitle: "ઇન્ટરેક્ટિવ લો શૂ ગ્રીડ",
      hoverTip: "ઉર્જા પ્રોફાઇલ અને ખૂટતા ક્ષેત્રો જોવા માટે ખાના પર હોવર કરો.",
      tabs: {
        dashboard: "સારાંશ અને ગ્રીડ",
        personality: "વ્યક્તિત્વ અને સંપત્તિ",
        lifestyle: "આરોગ્ય અને કારકિર્દી",
        remedies: "ઉપાયો અને ભવિષ્ય",
        all: "સંપૂર્ણ રિપોર્ટ"
      },
      disclaimer: "અસ્વીકરણ: આ અંકશાસ્ત્ર રિપોર્ટ માત્ર આત્મ-ચિંતન અને માર્ગદર્શન માટે છે. ભવિષ્યવાણીઓ ચોક્કસ પરિણામોને બદલે સંભાવનાઓ દર્શાવે છે.",
      strengths: "મુખ્ય શક્તિઓ",
      weaknesses: "સુધારવાના ક્ષેત્રો",
      hiddenTalents: "છુપાયેલી પ્રતિભા",
      innerNature: "આંતરિક સ્વભાવ",
      outerPersonality: "બાહ્ય વ્યક્તિત્વ",
      wealthRating: "ધન આકર્ષણ રેટિંગ",
      marriageCompat: "લગ્ન સુમેળ સ્તર",
      suggestions: "જીવનશૈલી માર્ગદર્શન",
      challenges: "જીવનના પડકારો અને અવરોધો",
      lucky: "શુભ પરિબળો",
      unlucky: "સાવચેતીના પરિબળો",
      remediesTitle: "ઊર્જા સંતુલન માટે ઉપાયો",
      forecastTitle: "વાર્ષિક ભવિષ્યવાણી",
      personalitySummary: "સમગ્ર વ્યક્તિત્વ સારાંશ",
      careerSuitability: "કારકિર્દી ક્ષેત્ર અનુકૂળતા",
      gridExplanation: "લો શૂ ગ્રીડ એક પ્રાચીન 3x3 જાદુઈ ચોરસ છે. તમારી જન્મ તારીખના આંકડાઓને તેના નિયત સ્થાને મુકાય છે, અને ખૂટતા અંકો જીવન પાઠ દર્શાવે છે."
    }
  }[lang];

  const LO_SHU_COORDINATES = [
    { num: 4, label: "4 - Wood / Southeast / Wealth & Planning", row: 0, col: 0 },
    { num: 9, label: "9 - Fire / South / Fame & Vitality", row: 0, col: 1 },
    { num: 2, label: "2 - Earth / Southwest / Marriage & Sensitivity", row: 0, col: 2 },
    { num: 3, label: "3 - Wood / East / Family & Creativity", row: 1, col: 0 },
    { num: 5, label: "5 - Earth / Center / Stability & Balance", row: 1, col: 1 },
    { num: 7, label: "7 - Metal / West / Children & Intuition", row: 1, col: 2 },
    { num: 8, label: "8 - Earth / Northeast / Knowledge & Practicality", row: 2, col: 0 },
    { num: 1, label: "1 - Water / North / Career & Communication", row: 2, col: 1 },
    { num: 6, label: "6 - Metal / Northwest / Luxury & Helpers", row: 2, col: 2 }
  ];

  return (
    <div className="space-y-12 print:space-y-6" ref={reportRef}>
      {/* 🌟 PREMIUM PRINT STYLES - Custom scoped inline style for flawless vector PDF prints */}
      <style>{`
        @media print {
          body {
            background: white !important;
            color: black !important;
            font-size: 12px !important;
          }
          .no-print {
            display: none !important;
          }
          .print-card {
            border: 1px solid #d4af37 !important;
            box-shadow: none !important;
            break-inside: avoid;
            page-break-inside: avoid;
            margin-bottom: 20px !important;
            background: white !important;
          }
          .print-header {
            text-align: center !important;
            margin-bottom: 30px !important;
          }
          .print-grid {
            display: grid !important;
            grid-template-columns: repeat(3, 1fr) !important;
            gap: 10px !important;
            max-width: 300px !important;
            margin: 0 auto !important;
          }
          .print-cell {
            border: 2px solid #d4af37 !important;
            aspect-ratio: 1 !important;
            display: flex !important;
            align-items: center !important;
            justify-content: center !important;
            font-weight: bold !important;
            font-size: 18px !important;
          }
        }
      `}</style>

      {/* 🔥 REPORT HEADER BANNER */}
      <div className="bg-gradient-to-br from-primary/10 via-surface to-card p-8 lg:p-12 rounded-3xl border-2 border-primary/20 relative overflow-hidden shadow-xl print-card">
        {/* Decorative Golden Ornaments */}
        <div className="absolute top-0 left-0 w-24 h-24 border-t-4 border-l-4 border-primary/30 rounded-tl-2xl pointer-events-none" />
        <div className="absolute top-0 right-0 w-24 h-24 border-t-4 border-r-4 border-primary/30 rounded-tr-2xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-24 h-24 border-b-4 border-l-4 border-primary/30 rounded-bl-2xl pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-24 h-24 border-b-4 border-r-4 border-primary/30 rounded-br-2xl pointer-events-none" />

        <div className="text-center max-w-3xl mx-auto space-y-4 print-header">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 text-primary text-xs font-bold uppercase tracking-[0.3em] rounded-full border border-primary/25">
            <Sparkles className="w-4 h-4" />
            LEO FAMILY ELITE NUMEROLOGY
          </div>
          <h2 className="text-3xl lg:text-5xl font-cinzel font-bold text-primary uppercase tracking-widest leading-tight">
            {t.reportTitle}
          </h2>
          <p className="text-text-secondary font-light italic text-sm lg:text-lg">
            {t.subtitle}
          </p>
          
          <div className="h-[2px] bg-gradient-to-r from-transparent via-primary/50 to-transparent w-full my-6" />

          {/* User Meta */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-left pt-2">
            <div className="bg-surface/60 p-4 rounded-xl border border-border/20">
              <span className="text-[10px] uppercase font-bold text-text-secondary/60 tracking-wider">Client Name</span>
              <p className="font-serif text-lg font-bold text-text-primary tracking-wide capitalize">{userName || 'Anonymous'}</p>
            </div>
            <div className="bg-surface/60 p-4 rounded-xl border border-border/20">
              <span className="text-[10px] uppercase font-bold text-text-secondary/60 tracking-wider">Date of Birth</span>
              <p className="font-mono text-lg font-bold text-text-primary">{report.personalInfo.dob}</p>
            </div>
            <div className="bg-surface/60 p-4 rounded-xl border border-border/20">
              <span className="text-[10px] uppercase font-bold text-text-secondary/60 tracking-wider">Current Age</span>
              <p className="text-lg font-bold text-text-primary">{report.personalInfo.age} Years</p>
            </div>
            <div className="bg-surface/60 p-4 rounded-xl border border-border/20">
              <span className="text-[10px] uppercase font-bold text-text-secondary/60 tracking-wider">Generation Profile</span>
              <p className="text-xs font-semibold text-text-secondary">{report.personalInfo.generation}</p>
            </div>
          </div>
        </div>
      </div>

      {/* 🎛️ STICKY ACTIONS BAR (No Print) */}
      <div className="no-print bg-card/90 backdrop-blur-md sticky top-4 z-40 p-4 rounded-2xl border border-border/20 shadow-md flex flex-wrap gap-4 items-center justify-between">
        <div className="flex flex-wrap items-center gap-2">
          {/* Language selection pills */}
          <span className="text-xs font-bold text-text-secondary flex items-center gap-1 uppercase tracking-wider mr-2">
            <Languages className="w-4 h-4 text-primary" /> {t.language}:
          </span>
          {(['en', 'hi', 'gu'] as Language[]).map(l => (
            <button
              key={l}
              onClick={() => setLang(l)}
              className={`px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider border transition-all ${
                lang === l 
                  ? 'bg-primary text-background border-primary shadow-sm' 
                  : 'bg-surface text-text-secondary border-border/20 hover:bg-surface/80'
              }`}
            >
              {l === 'en' ? 'EN' : l === 'hi' ? 'HI' : 'GU'}
            </button>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-5 py-2.5 bg-primary hover:brightness-110 text-background font-bold text-xs uppercase tracking-wider rounded-xl transition-all shadow-md"
          >
            <Printer className="w-4 h-4" />
            {t.downloadPdf}
          </button>
          <button
            onClick={handleSaveLocally}
            className={`flex items-center gap-2 px-5 py-2.5 font-bold text-xs uppercase tracking-wider rounded-xl transition-all border shadow-sm ${
              isSaved 
                ? 'bg-emerald-500 text-white border-emerald-500' 
                : 'bg-surface hover:brightness-110 text-text-primary border-border/20'
            }`}
          >
            <Bookmark className="w-4 h-4" />
            {isSaved ? t.saved : t.saveReport}
          </button>
          
          <div className="flex items-center gap-1 border-l border-border/20 pl-3 ml-1">
            <button 
              onClick={() => handleShare('whatsapp')}
              className="p-2 hover:bg-emerald-500/10 text-emerald-500 rounded-full transition-all" 
              title="Share on WhatsApp"
            >
              <Share2 className="w-4 h-4" />
            </button>
            <button 
              onClick={() => handleShare('x')}
              className="p-2 hover:bg-text-primary/10 text-text-primary rounded-full transition-all" 
              title="Share on X"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          <button
            onClick={onClose}
            className="p-2 hover:bg-rose-500/10 text-rose-500 rounded-full transition-all border border-rose-500/20 ml-2"
            title={t.close}
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* 🧭 TABS NAVIGATION FOR CORE AREAS */}
      <div className="no-print flex border-b border-border/20 overflow-x-auto scrollbar-none scroll-smooth">
        {(['dashboard', 'personality', 'lifestyle', 'remedies', 'all'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveThemeTab(tab)}
            className={`flex-1 min-w-[120px] py-4 text-center text-xs font-bold uppercase tracking-widest border-b-2 transition-all ${
              activeThemeTab === tab
                ? 'border-primary text-primary bg-primary/5 font-bold'
                : 'border-transparent text-text-secondary hover:text-text-primary'
            }`}
          >
            {t.tabs[tab]}
          </button>
        ))}
      </div>

      {/* 🔮 REPORT CONTENT PANEL */}
      <div className="space-y-12">
        {/* ==================== SUMMARY & GRID TAB ==================== */}
        {(activeThemeTab === 'dashboard' || activeThemeTab === 'all') && (
          <div className="space-y-12 animate-fade-in">
            {/* Section 1: Dashboard Summary Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Interactive Lo Shu Grid Card */}
              <div className="lg:col-span-1 bg-white p-6 rounded-3xl border border-amber-300/20 shadow-md print-card">
                <div className="space-y-4 mb-6">
                  <h3 className="text-lg font-cinzel font-bold text-amber-700 flex items-center gap-2 uppercase tracking-wider">
                    <Grid3X3 className="w-5 h-5" />
                    {t.loShuTitle}
                  </h3>
                  <p className="text-xs text-zinc-500 leading-relaxed font-light">
                    {t.gridExplanation}
                  </p>
                </div>

                {/* Lo Shu Grid Canvas */}
                <div className="max-w-[320px] mx-auto print-grid">
                  <div className="grid grid-cols-3 gap-3 bg-gradient-to-br from-amber-50 to-white p-3 rounded-2xl border-2 border-amber-200/50 shadow-inner">
                    {LO_SHU_COORDINATES.map((cell) => {
                      const count = report.gridCounts[cell.num] || 0;
                      const displayDigits = count > 0 ? cell.num.toString().repeat(count) : "";
                      const isHovered = hoveredNumber === cell.num;

                      return (
                        <div
                          key={cell.num}
                          onMouseEnter={() => setHoveredNumber(cell.num)}
                          onMouseLeave={() => setHoveredNumber(null)}
                          className={`aspect-square rounded-xl flex flex-col items-center justify-center relative cursor-pointer transition-all duration-300 print-cell ${
                            count > 0 
                              ? 'bg-gradient-to-br from-amber-400 via-amber-500 to-amber-600 text-white shadow-lg shadow-amber-500/20 scale-100 hover:scale-105 border-0' 
                              : 'bg-white text-zinc-300 border border-zinc-100 shadow-sm'
                          } ${isHovered ? 'ring-4 ring-amber-300 ring-offset-2' : ''}`}
                        >
                          <span className={`absolute top-1 left-2 text-[8px] font-mono ${count > 0 ? 'text-amber-100' : 'text-zinc-300'}`}>
                            {cell.num}
                          </span>
                          <span className={`text-xl font-cinzel font-bold ${count > 0 ? 'text-white' : 'text-zinc-100'}`}>
                            {displayDigits || cell.num}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                <div className="mt-4 p-3 bg-amber-50/50 rounded-xl border border-amber-200/30 text-center">
                  <p className="text-[10px] text-amber-800 flex items-center justify-center gap-1 font-medium">
                    <Info className="w-3.5 h-3.5 shrink-0" />
                    {t.hoverTip}
                  </p>
                </div>
              </div>

              {/* Personal Info Bento Card */}
              <div className="lg:col-span-2 bg-white p-6 rounded-3xl border border-amber-300/20 shadow-md print-card">
                <h3 className="text-lg font-cinzel font-bold text-amber-700 flex items-center gap-2 uppercase tracking-wider mb-6">
                  <User className="w-5 h-5" />
                  Section 1: Personal Energy Indicators
                </h3>

                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider block mb-1">
                      {t.psychic}
                    </span>
                    <span className="text-3xl font-cinzel font-bold text-amber-600 gold-glow-text">
                      {report.personalInfo.driver}
                    </span>
                    <p className="text-[10px] text-zinc-500 mt-2">Core personality, drives, strengths.</p>
                  </div>

                  <div className="p-4 bg-gradient-to-br from-amber-50 to-white rounded-xl border border-amber-200/30">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider block mb-1">
                      {t.destiny}
                    </span>
                    <span className="text-3xl font-cinzel font-bold text-amber-600 gold-glow-text">
                      {report.personalInfo.conductor}
                    </span>
                    <p className="text-[10px] text-zinc-500 mt-2">Life path, calling, ultimate target.</p>
                  </div>

                  <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider block mb-1">
                      {t.lifePath}
                    </span>
                    <span className="text-3xl font-cinzel font-bold text-zinc-800">
                      {report.personalInfo.lifePath}
                    </span>
                    <p className="text-[10px] text-zinc-500 mt-2">The blueprint route you traverse.</p>
                  </div>

                  <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider block mb-1">
                      {t.personalYear}
                    </span>
                    <span className="text-2xl font-bold text-zinc-800">
                      {report.personalInfo.personalYear}
                    </span>
                    <p className="text-[10px] text-zinc-500 mt-2">Current annual energy vibration.</p>
                  </div>

                  <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider block mb-1">
                      {t.personalMonth}
                    </span>
                    <span className="text-2xl font-bold text-zinc-800">
                      {report.personalInfo.personalMonth}
                    </span>
                    <p className="text-[10px] text-zinc-500 mt-2">Current monthly energy vibration.</p>
                  </div>

                  <div className="p-4 bg-zinc-50 rounded-xl border border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider block mb-1">
                      {t.birthElement}
                    </span>
                    <span className="text-sm font-bold text-zinc-800 block mt-2">
                      {report.personalInfo.birthElement}
                    </span>
                  </div>
                </div>

                <div className="mt-6 p-4 bg-amber-50/30 rounded-2xl border border-amber-200/20">
                  <div className="flex items-center gap-2 mb-2">
                    <Scale className="w-4.5 h-4.5 text-amber-500" />
                    <h4 className="text-xs font-bold uppercase tracking-wider text-amber-800">{t.yinYang}</h4>
                  </div>
                  <p className="text-xs text-zinc-600 leading-relaxed font-light">
                    {report.personalInfo.yinYangBalance.description}
                  </p>
                  <div className="flex items-center gap-6 mt-3">
                    <div className="flex items-center gap-1.5 text-[10px] font-bold text-zinc-500 uppercase">
                      <span className="w-2.5 h-2.5 rounded-full bg-zinc-800 inline-block" />
                      Yin: {report.personalInfo.yinYangBalance.yin}
                    </div>
                    <div className="flex items-center gap-1.5 text-[10px] font-bold text-zinc-500 uppercase">
                      <span className="w-2.5 h-2.5 rounded-full bg-amber-400 inline-block animate-pulse" />
                      Yang: {report.personalInfo.yinYangBalance.yang}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 5: Dominant Energy / Score Dashboard */}
            <div className="bg-gradient-to-br from-[#FAF9F6] to-white p-8 rounded-3xl border border-amber-300/25 shadow-lg print-card">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
                <div>
                  <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest">
                    Section 5: Dominant Energy & Summary Dashboard
                  </h3>
                  <p className="text-xs text-zinc-500 mt-1 font-light">
                    Your complete elemental distribution and macro ratings.
                  </p>
                </div>
                <div className="flex items-center gap-3 bg-white px-6 py-3 rounded-2xl border border-amber-200 shadow-inner">
                  <Award className="w-6 h-6 text-amber-500" />
                  <div className="text-left">
                    <span className="text-[10px] text-zinc-400 uppercase font-bold tracking-wider block">Life Harmony Score</span>
                    <span className="text-2xl font-cinzel font-bold text-amber-600">{report.dominantEnergy.overallScore} / 100</span>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Element Distribution Gauges */}
                <div className="space-y-4">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500">Element Distribution</h4>
                  <div className="space-y-3">
                    {Object.entries(report.dominantEnergy.elements).map(([elementName, detail]) => {
                      if (elementName === 'Water_element') return null; // Avoid duplicate rendering
                      return (
                        <div key={elementName} className="space-y-1 bg-white p-3 rounded-xl border border-zinc-100 shadow-sm">
                          <div className="flex justify-between items-center text-xs">
                            <span className="font-semibold text-zinc-700 capitalize">{elementName}</span>
                            <span className="text-zinc-500 text-[10px] font-bold bg-amber-50 text-amber-700 px-2 py-0.5 rounded-md">
                              {detail.percent}% - {detail.status}
                            </span>
                          </div>
                          {/* Custom Styled Golden Progress Bar */}
                          <div className="w-full bg-zinc-100 h-2 rounded-full overflow-hidden">
                            <div 
                              className="h-full bg-gradient-to-r from-amber-400 to-amber-600 rounded-full transition-all duration-1000" 
                              style={{ width: `${detail.percent}%` }}
                            />
                          </div>
                          <p className="text-[10px] text-zinc-400 font-light italic">{detail.desc}</p>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Dashboard Ratings stars block */}
                <div className="space-y-4">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500">Summary Dimension Metrics</h4>
                  <div className="grid grid-cols-2 gap-4">
                    {Object.entries(report.dashboardRatings).map(([dimension, value]) => {
                      if (dimension === 'overallScore') return null;
                      return (
                        <div key={dimension} className="bg-white p-4 rounded-2xl border border-zinc-100 shadow-sm flex flex-col justify-between">
                          <span className="text-[10px] uppercase font-bold text-zinc-400 tracking-wider capitalize">
                            {dimension}
                          </span>
                          <div className="flex gap-1.5 mt-2">
                            {Array.from({ length: 5 }).map((_, i) => (
                              <Star 
                                key={i} 
                                className={`w-4 h-4 ${
                                  i < value ? 'text-amber-500 fill-amber-500' : 'text-zinc-200'
                                }`} 
                              />
                            ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            </div>

            {/* Interactive Lo Shu hovered element info popover (dynamic) */}
            <AnimatePresence>
              {hoveredNumber !== null && (
                <motion.div 
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 10 }}
                  className="p-5 bg-amber-50 border border-amber-300 rounded-2xl shadow-lg relative overflow-hidden"
                >
                  <div className="absolute right-0 top-0 p-3 opacity-10">
                    <Sparkle className="w-12 h-12 text-amber-500" />
                  </div>
                  <h4 className="text-sm font-bold text-amber-800 uppercase tracking-widest mb-2">
                    Quick Peek: Number {hoveredNumber} - {report.numberAnalysis[hoveredNumber - 1]?.title}
                  </h4>
                  <p className="text-xs text-zinc-700 leading-relaxed">
                    {report.numberAnalysis[hoveredNumber - 1]?.meaning}
                  </p>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Section 6: Arrow Analysis (detected active planes) */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 6: Arrow Analysis (Axes of Energy)
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {report.arrows.map((arrow, idx) => (
                  <div 
                    key={idx}
                    className={`p-5 rounded-2xl border transition-all ${
                      arrow.isActive 
                        ? 'bg-amber-50/50 border-amber-300/40 shadow-sm' 
                        : arrow.isNegative 
                          ? 'bg-rose-50/30 border-rose-100' 
                          : 'bg-zinc-50 border-zinc-100'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2">
                        <CircleDot className={`w-4 h-4 ${arrow.isActive ? 'text-amber-500' : 'text-zinc-400'}`} />
                        <h4 className="font-bold text-sm text-zinc-800">{arrow.name}</h4>
                      </div>
                      <span className={`text-[9px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider ${
                        arrow.isActive 
                          ? 'bg-amber-500 text-white' 
                          : arrow.isNegative 
                            ? 'bg-rose-100 text-rose-700' 
                            : 'bg-zinc-200 text-zinc-600'
                      }`}>
                        {arrow.isActive ? 'Active' : arrow.isNegative ? 'Missing Arrow' : 'Partial'}
                      </span>
                    </div>

                    <p className="text-xs text-zinc-600 leading-relaxed font-light mb-4">
                      {arrow.meaning}
                    </p>

                    <div className="space-y-2 pt-2 border-t border-zinc-200/50 text-[11px] text-zinc-500">
                      <div><strong className="text-zinc-700 font-semibold">Planes:</strong> {arrow.numbers.join('-')}</div>
                      {arrow.isActive && (
                        <>
                          <div><strong className="text-zinc-700 font-semibold">Positive Impact:</strong> {arrow.impact}</div>
                          <div><strong className="text-zinc-700 font-semibold">Career Guidance:</strong> {arrow.career}</div>
                          <div><strong className="text-zinc-700 font-semibold">Relationship:</strong> {arrow.relationship}</div>
                        </>
                      )}
                      <div><strong className="text-zinc-700 font-semibold">Advice:</strong> {arrow.advice}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* ==================== PERSONALITY & WEALTH TAB ==================== */}
        {(activeThemeTab === 'personality' || activeThemeTab === 'all') && (
          <div className="space-y-12 animate-fade-in">
            {/* Section 7: Deep Personality Analysis */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 7: Deep Personality Analysis
              </h3>
              
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Communication Style</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.communication}</p>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Thinking Pattern</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.thinking}</p>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Decision Making</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.decisionMaking}</p>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Learning Style</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.learning}</p>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Emotional Intelligence</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.emotionalIntelligence}</p>
                  </div>
                  <div className="space-y-1">
                    <span className="text-[10px] uppercase font-bold text-amber-600 tracking-wider">Social Nature</span>
                    <p className="text-xs text-zinc-600 leading-relaxed font-light">{report.personality.socialNature}</p>
                  </div>
                </div>

                <div className="p-6 bg-gradient-to-br from-amber-50 to-white rounded-2xl border border-amber-200/30 shadow-inner mt-8">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-5 h-5 text-amber-500" />
                    <h4 className="text-sm font-bold uppercase tracking-wider text-amber-800">
                      {t.personalitySummary}
                    </h4>
                  </div>
                  <p className="text-xs text-zinc-700 leading-relaxed font-serif italic">
                    {report.aiNarrative}
                  </p>
                </div>
              </div>
            </div>

            {/* Section 8: Character Analysis */}
            <div className="bg-[#FAF9F6] p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 8: Character Analysis & Internal Dynamics
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Strengths & Weaknesses list block */}
                <div className="space-y-6">
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-700 flex items-center gap-1.5 mb-3">
                      <Star className="w-4 h-4 text-emerald-500 fill-emerald-500" />
                      {t.strengths}
                    </h4>
                    <ul className="space-y-2">
                      {report.character.strengths.map((str, i) => (
                        <li key={i} className="text-xs text-zinc-600 flex items-center gap-2">
                          <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full shrink-0" />
                          {str}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-rose-700 flex items-center gap-1.5 mb-3">
                      <ShieldAlert className="w-4 h-4 text-rose-500" />
                      {t.weaknesses}
                    </h4>
                    <ul className="space-y-2">
                      {report.character.weaknesses.map((weak, i) => (
                        <li key={i} className="text-xs text-zinc-600 flex items-center gap-2">
                          <span className="w-1.5 h-1.5 bg-rose-500 rounded-full shrink-0" />
                          {weak}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Behavioral Patterns */}
                <div className="space-y-4 text-xs text-zinc-600 leading-relaxed">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">
                      {t.hiddenTalents}
                    </strong>
                    <p className="font-light">{report.character.hiddenTalents}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">
                      {t.innerNature}
                    </strong>
                    <p className="font-light">{report.character.innerNature}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">
                      {t.outerPersonality}
                    </strong>
                    <p className="font-light">{report.character.outerPersonality}</p>
                  </div>
                  <div className="grid grid-cols-3 gap-2 pt-2 border-t border-zinc-200">
                    <div>
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Success Behaviour</span>
                      <p className="text-[10px] font-light leading-snug">{report.character.successBehavior}</p>
                    </div>
                    <div>
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">Under Pressure</span>
                      <p className="text-[10px] font-light leading-snug">{report.character.pressureBehavior}</p>
                    </div>
                    <div>
                      <span className="text-[9px] font-bold text-zinc-400 uppercase tracking-wider block mb-1">During Failure</span>
                      <p className="text-[10px] font-light leading-snug">{report.character.failureBehavior}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 10: Wealth Analysis */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <div className="flex flex-col md:flex-row justify-between md:items-center gap-6 mb-6">
                <div>
                  <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest">
                    Section 10: Wealth & Financial Mindset
                  </h3>
                  <p className="text-xs text-zinc-500 mt-1 font-light">
                    How numbers shape your luxury attraction and savings blueprint.
                  </p>
                </div>
                <div className="flex items-center gap-2 bg-amber-50 px-5 py-2 rounded-xl border border-amber-200">
                  <DollarSign className="w-5 h-5 text-amber-600" />
                  <div>
                    <span className="text-[9px] font-bold text-amber-800 uppercase tracking-wider block">{t.wealthRating}</span>
                    <span className="text-sm font-bold text-amber-700">{report.wealth.rating} ({report.wealth.score}/100)</span>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Money Mindset</strong>
                    <p>{report.wealth.moneyMindset}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Savings Habit</strong>
                    <p>{report.wealth.savingsHabit}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Financial Growth</strong>
                    <p>{report.wealth.financialGrowth}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Investment Nature</strong>
                    <p>{report.wealth.investmentNature}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Luxury Attraction</strong>
                    <p>{report.wealth.luxuryAttraction}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4 pt-2 border-t border-zinc-100">
                    <div>
                      <strong className="text-zinc-800 uppercase text-[9px] font-bold block mb-1">Property Potential</strong>
                      <p className="text-[10px] leading-snug">{report.wealth.propertyPotential}</p>
                    </div>
                    <div>
                      <strong className="text-zinc-800 uppercase text-[9px] font-bold block mb-1">Passive Income Scope</strong>
                      <p className="text-[10px] leading-snug">{report.wealth.passiveIncome}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ==================== HEALTH & LIFESTYLE TAB ==================== */}
        {(activeThemeTab === 'lifestyle' || activeThemeTab === 'all') && (
          <div className="space-y-12 animate-fade-in">
            {/* Section 9: Career Analysis */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-4">
                Section 9: Professional Career & Suitability Analysis
              </h3>
              <p className="text-xs text-zinc-500 mb-6 font-light">
                {report.career.advice}
              </p>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {report.career.suitability.map((item, i) => (
                  <div key={i} className="p-4 bg-zinc-50 rounded-2xl border border-zinc-100 shadow-sm text-center flex flex-col justify-between">
                    <span className="text-[10px] font-bold uppercase text-zinc-500 tracking-wider block mb-2">
                      {item.field}
                    </span>
                    <div>
                      <span className="text-2xl font-cinzel font-bold text-amber-600 block mb-2">
                        {item.percentage}%
                      </span>
                      <div className="w-full bg-zinc-200 h-1 rounded-full overflow-hidden">
                        <div className="h-full bg-amber-500 rounded-full" style={{ width: `${item.percentage}%` }} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 11: Relationships & Marriage */}
            <div className="bg-[#FAF9F6] p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest">
                  Section 11: Love, Marriage & Relationship Analysis
                </h3>
                <span className="text-xs font-bold text-amber-800 bg-amber-100 px-3 py-1 rounded-full border border-amber-200 shrink-0">
                  {t.marriageCompat}: {report.relationship.compatibilityLevel}%
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-3">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Love Nature</strong>
                    <p>{report.relationship.loveNature}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Marriage Compatibility</strong>
                    <p>{report.relationship.marriageCompatibility}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Communication Style</strong>
                    <p>{report.relationship.communication}</p>
                  </div>
                </div>
                <div className="space-y-3">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Trust & Guardedness</strong>
                    <p>{report.relationship.trust}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Domestic & Family Life</strong>
                    <p>{report.relationship.familyLife}</p>
                  </div>
                  <div className="p-4 bg-white rounded-xl border border-zinc-100">
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Relationship Advice</strong>
                    <p className="italic">"{report.relationship.advice}"</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 12: Health tendencies */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 12: Health & Physical Tendencies
              </h3>

              <div className="p-4 bg-zinc-50 border-l-4 border-amber-500 rounded-r-xl mb-6">
                <p className="text-xs text-zinc-500 font-light leading-relaxed">
                  <strong>Important Notice:</strong> {t.disclaimer}
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-3">
                  <h4 className="text-[11px] uppercase font-bold text-zinc-400 tracking-wider">Physical Tendencies</h4>
                  <ul className="space-y-2">
                    {report.health.tendencies.map((tend, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <Activity className="w-4 h-4 text-amber-500 shrink-0" />
                        <span>{tend}</span>
                      </li>
                    ))}
                  </ul>
                  <div className="pt-3 border-t border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 block mb-1">Digestion Health</span>
                    <p>{report.health.digestion}</p>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-[11px] uppercase font-bold text-zinc-400 tracking-wider">{t.suggestions}</h4>
                  <ul className="space-y-2">
                    {report.health.suggestions.map((sug, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <span className="w-1.5 h-1.5 bg-amber-500 rounded-full shrink-0" />
                        <span>{sug}</span>
                      </li>
                    ))}
                  </ul>
                  <div className="pt-3 border-t border-zinc-100">
                    <span className="text-[10px] uppercase font-bold text-zinc-400 block mb-1">Stress Levels</span>
                    <p>{report.health.stressLevels}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ==================== REMEDIES & FORECAST TAB ==================== */}
        {(activeThemeTab === 'remedies' || activeThemeTab === 'all') && (
          <div className="space-y-12 animate-fade-in">
            {/* Section 13: Spiritual Analysis */}
            <div className="bg-white p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 13: Spiritual Analysis & Past Karma
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Intuition levels</strong>
                    <p>{report.spiritual.intuition}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Meditation Ability</strong>
                    <p>{report.spiritual.meditationAbility}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Past Life Connection</strong>
                    <p>{report.spiritual.pastLife}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Life Lessons</strong>
                    <p>{report.spiritual.lifeLessons}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Ultimate Purpose</strong>
                    <p>{report.spiritual.purpose}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Karma Pattern</strong>
                    <p>{report.spiritual.karma}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 14: Life Challenges */}
            <div className="bg-[#FAF9F6] p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                {t.challenges}
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-3">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Biggest Challenge</strong>
                    <p>{report.challenges.biggest}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Hidden Obstacle / Enemy</strong>
                    <p>{report.challenges.hiddenEnemy}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Self-Limiting Beliefs</strong>
                    <p>{report.challenges.beliefs}</p>
                  </div>
                </div>
                <div className="space-y-3">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Transformation Cycle</strong>
                    <p>{report.challenges.transformation}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Mental Blocks & Fears</strong>
                    <p>{report.challenges.blocks}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 15 & 16: Lucky/Unlucky Factors */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* Lucky factors */}
              <div className="bg-white p-6 rounded-3xl border border-amber-300/20 shadow-md print-card">
                <h3 className="text-lg font-cinzel font-bold text-amber-700 uppercase tracking-wider mb-4">
                  {t.lucky}
                </h3>
                <div className="grid grid-cols-2 gap-4 text-xs text-zinc-600">
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Lucky Numbers</strong>
                    <p className="font-mono">{report.luckyFactors.numbers.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Auspicious Dates</strong>
                    <p className="font-mono">{report.luckyFactors.dates.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Lucky Days</strong>
                    <p>{report.luckyFactors.days.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Lucky Colors</strong>
                    <p>{report.luckyFactors.colors.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Directions</strong>
                    <p>{report.luckyFactors.directions.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 text-[9px] font-bold uppercase block mb-1">Gemstones</strong>
                    <p>{report.luckyFactors.gemstones.join(', ')}</p>
                  </div>
                </div>
              </div>

              {/* Unlucky factors */}
              <div className="bg-rose-50/20 p-6 rounded-3xl border border-rose-100 shadow-sm print-card">
                <h3 className="text-lg font-cinzel font-bold text-rose-700 uppercase tracking-wider mb-4">
                  {t.unlucky}
                </h3>
                <div className="grid grid-cols-2 gap-4 text-xs text-zinc-600">
                  <div>
                    <strong className="text-rose-800 text-[9px] font-bold uppercase block mb-1">Numbers to Avoid</strong>
                    <p className="font-mono">{report.unluckyFactors.numbers.join(', ') || 'None'}</p>
                  </div>
                  <div>
                    <strong className="text-rose-800 text-[9px] font-bold uppercase block mb-1">Risk Areas</strong>
                    <p>{report.unluckyFactors.riskAreas.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-rose-800 text-[9px] font-bold uppercase block mb-1">Weak Periods</strong>
                    <p>{report.unluckyFactors.weakPeriods.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-rose-800 text-[9px] font-bold uppercase block mb-1">Negative Habits</strong>
                    <p>{report.unluckyFactors.habitsToAvoid.join(', ')}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 18: Annual Forecast */}
            <div className="bg-[#FAF9F6] p-8 rounded-3xl border border-amber-300/20 shadow-md print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6">
                Section 18: {t.forecastTitle} ({report.annualPrediction.year})
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-4">
                  <div className="p-4 bg-white rounded-xl border border-amber-200">
                    <span className="text-[10px] font-bold text-amber-800 uppercase tracking-wider block mb-1">Your Personal Year Number</span>
                    <span className="text-3xl font-cinzel font-bold text-amber-600">{report.annualPrediction.personalYearNumber}</span>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Career & Growth</strong>
                    <p>{report.annualPrediction.career}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Financial Inflow</strong>
                    <p>{report.annualPrediction.money}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Relationships & Love</strong>
                    <p>{report.annualPrediction.love}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Health Trends</strong>
                    <p>{report.annualPrediction.health}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Travel Forecast</strong>
                    <p>{report.annualPrediction.travel}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 19: Remedies & Daily Rituals */}
            <div className="bg-gradient-to-br from-amber-50/50 via-white to-[#FAF9F6] p-8 rounded-3xl border-2 border-amber-400/25 shadow-lg print-card">
              <h3 className="text-xl font-cinzel font-bold text-amber-700 uppercase tracking-widest mb-6 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-amber-500" />
                Section 19: {t.remediesTitle}
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-xs text-zinc-600 leading-relaxed font-light">
                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Morning Routine</strong>
                    <p>{report.remedies.morningRoutine}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Meditation Practice</strong>
                    <p>{report.remedies.meditation}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Custom Divine Affirmations</strong>
                    <ul className="space-y-2 mt-2">
                      {report.remedies.affirmations.map((aff, i) => (
                        <li key={i} className="flex items-center gap-2 italic">
                          <span className="w-1.5 h-1.5 bg-amber-500 rounded-full shrink-0" />
                          <span>"{aff}"</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                <div className="space-y-4">
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Auspicious Colors to Wear</strong>
                    <p>{report.remedies.colors.join(', ')}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Acts of Charity (Moong dal, Wed, etc)</strong>
                    <p>{report.remedies.charity}</p>
                  </div>
                  <div>
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Vedic Mantras to Chant</strong>
                    <p>{report.remedies.mantras.join(', ')}</p>
                  </div>
                  <div className="p-4 bg-white rounded-xl border border-amber-100 shadow-inner">
                    <strong className="text-zinc-800 uppercase text-[10px] font-bold block mb-1">Elite Gemstone Guidance (Optional)</strong>
                    <p className="italic leading-relaxed">
                      {report.remedies.gemstoneGuidance}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ⚠️ FOOTER MEDICAL DISCLAIMER */}
      <div className="pt-8 border-t border-zinc-200 text-[10px] text-zinc-400 leading-relaxed italic text-center print-card">
        {t.disclaimer}
      </div>
    </div>
  );
}
