import { MediaItem } from './MediaTypes';
import { extractYoutubeId, getYoutubeThumbnail } from './MediaHelpers';

const DEFAULT_NOW = "2026-07-17T00:00:00Z";

/**
 * Robust initial list of high-vibrational media items for LEO Family.
 * Includes student success stories, class lectures, webinars, and short video reels.
 */
export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  // LECTURES & FOUNDATIONAL CONTENT
  {
    id: "RcmLxAECJAc",
    title: "How Compound Planetary Frequencies Shape Your Entire Career",
    subtitle: "Chaldean Numerology Level 1 Masterclass",
    description: "In this comprehensive class, Raajeev Singh Chauhann explains how Chaldean planetary frequencies interact with your name and birth dates. Learn how double-digit compound numbers generate energetic currents that directly dictate your corporate success, signature power, and financial breakthroughs.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'maxresdefault'),
    category: "Free Numerology Classes",
    collection: ["free-classes", "numerology-masterclass", "editors-picks", "popular"],
    instructor: "Raajeev Singh Chauhann",
    duration: "18:45",
    publishedDate: "2026-05-10",
    language: "Hindi",
    tags: ["Planetary Frequencies", "Chaldean Science", "Corporate Success", "Name Alignment"],
    featured: true,
    recommended: true,
    difficulty: "Beginner",
    visibility: "public",
    priority: 100,
    seoTitle: "Chaldean Planetary Frequencies and Career Success - Raajeev Singh",
    seoDescription: "Learn how double digit compound name numbers interact with your destiny grids to dictate corporate and financial breakthroughs.",
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 184200,
    watchTime: 1240000,
    likes: 12400,
    learnings: [
      "Understand the difference between single-digit master numbers and compound numbers.",
      "How to calculate your Name Vibration number and align it to your birth grid.",
      "Why professional breakthroughs depend heavily on your active signature structure.",
      "Real-world case studies of massive film and corporate business alignments."
    ],
    relatedCourseId: "c1",
    relatedCourseName: "Complete Chaldean Numerology Masterclass",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20watched%20your%20Compound%20Planetary%20Frequencies%20class."
  },
  {
    id: "PLOFld0SYjqbZ-wCREGBGP4d96TDm7ZbDf",
    title: "Mastering Vastu Energetics & Non-Destructive Solutions",
    subtitle: "Complete Vastu Shastra Training Playlist",
    description: "Discover the profound science of Vastu Shastra without the need for demolition or reconstruction. This masterclass playlist guides you through balancing energetic directions, optimizing positive planetary nodes, and utilizing brass and gemstone corrective implants to enhance workplace health and home harmony.",
    youtubeUrl: "https://youtube.com/playlist?list=PLOFld0SYjqbZ-wCREGBGP4d96TDm7ZbDf",
    youtubeId: "PLOFld0SYjqbZ-wCREGBGP4d96TDm7ZbDf",
    thumbnail: getYoutubeThumbnail("PLOFld0SYjqbZ-wCREGBGP4d96TDm7ZbDf", 'maxresdefault'),
    category: "Vastu",
    collection: ["vastu", "editors-picks", "trending"],
    instructor: "Raajeev Singh Chauhann",
    duration: "12 Videos",
    publishedDate: "2026-04-12",
    language: "Hindi",
    tags: ["Vastu Correction", "Non-Destructive Vastu", "Industrial Space Harmony"],
    featured: false,
    isPlaylist: true,
    difficulty: "Intermediate",
    visibility: "public",
    priority: 90,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 340000,
    watchTime: 4080000,
    likes: 21800,
    learnings: [
      "Identify toxic planetary directions and weak elemental quadrants in any property.",
      "Apply high-vibrational gemstone placements to cure structural imbalances.",
      "The role of center-point 'Brahmasthan' stability in continuous business profitability.",
      "Simple, cost-effective brass-wire corrections for south-facing properties."
    ],
    relatedCourseId: "c6",
    relatedCourseName: "Vastu Shastra Foundation Certification",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20am%20interested%20in%20a%20Vastu%20Consultation."
  },
  {
    id: "RcmLxAECJAc-astrology",
    title: "Demystifying Saturn and Rahu Dasha Remediations",
    subtitle: "Vedic Astrology Dasha Cycles",
    description: "Saturn and Rahu cycles do not have to mean hardship. Raajeev Singh Chauhann demystifies active astrological dasha phases, detailing how exact gemstone selection, Vedic mantras, and charity schedules can turn obstacle phases into times of intense expansion.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'hqdefault'),
    category: "Astrology",
    collection: ["astrology", "trending"],
    instructor: "Raajeev Singh Chauhann",
    duration: "12:30",
    publishedDate: "2026-03-24",
    language: "Hindi",
    tags: ["Planetary Dashas", "Saturn Remediation", "Rahu Dasha Remedies", "Gemstone Cures"],
    featured: true,
    difficulty: "Advanced",
    visibility: "public",
    priority: 85,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 98000,
    watchTime: 1225000,
    likes: 8400,
    learnings: [
      "The real purpose of Saturn cycles: psychological discipline and long-term security.",
      "How to avoid synthetic gemstones that intensify negative planetary nodes.",
      "Simple, active charity regimes aligned with specific days and times.",
      "Combining gemstone science with Chaldean birth grid calculations."
    ],
    relatedCourseId: "c7",
    relatedCourseName: "Astrology Essentials & Dashas",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20am%20undergoing%20a%20challenging%20Dasha%20cycle."
  },
  {
    id: "RcmLxAECJAc-motivation",
    title: "Conquering Subconscious Fears and Planetary Shadows",
    subtitle: "Spiritual Willpower & Mindset Training",
    description: "In this powerful motivational session, Raajeev Singh Chauhann outlines how planetary shadows affect our mental frameworks. He shares five practical daily habits designed to reprogram your response to fear, restore your self-belief, and build unwavering mental toughness.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'hqdefault'),
    category: "Motivational Talks",
    collection: ["motivation", "editors-picks"],
    instructor: "Raajeev Singh Chauhann",
    duration: "14:50",
    publishedDate: "2026-05-18",
    language: "Hindi",
    tags: ["Planetary Shadows", "Fear Programming", "Mental Toughness", "Daily Sadhana"],
    featured: false,
    difficulty: "All Levels",
    visibility: "public",
    priority: 70,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 115000,
    watchTime: 1725000,
    likes: 9200,
    learnings: [
      "How planetary alignments influence neural thought loops.",
      "The exact hour of 'Brahma Muhurta' and its role in rebuilding willpower.",
      "How to identify if your physical home environments are inducing brain fog.",
      "Techniques to create an energetic barrier around your professional space."
    ],
    relatedCourseId: "c8",
    relatedCourseName: "Meditation & Spiritual Awakening Certification",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20build%20mental%20peace."
  },
  {
    id: "RcmLxAECJAc-meditation",
    title: "A Complete 10-Minute Daily Breath-Control Sadhana",
    subtitle: "Guided Vedic Pranayama Session",
    description: "A step-by-step guidance on authentic Vedic breath regulation (Pranayama). Designed for busy professionals, entrepreneurs, and students to calm active central nervous systems, reset adrenal fatigue, and focus raw planetary energies for mental clarity.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'hqdefault'),
    category: "Meditation",
    collection: ["meditation", "editors-picks"],
    instructor: "Raajeev Singh Chauhann",
    duration: "10:15",
    publishedDate: "2026-02-14",
    language: "Hindi",
    tags: ["Pranayama", "Breathwork", "Pranic Respiration", "Mental Peace"],
    featured: false,
    difficulty: "Beginner",
    visibility: "public",
    priority: 80,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 152000,
    watchTime: 1550400,
    likes: 11400,
    learnings: [
      "The dual-nostril alternate breathing pattern for hemispheric brain harmony.",
      "How slow, structured retention (Kumbhaka) resets physical stress responses.",
      "Selecting the ideal natural posture to avoid energetic spine blocks.",
      "How to integrate breathwork before performing key numerology calculations."
    ],
    relatedCourseId: "c8",
    relatedCourseName: "Meditation & Spiritual Awakening Certification",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20learn%20Pranayama."
  },
  {
    id: "RcmLxAECJAc-business",
    title: "Chaldean Strategies for Corporate Names and Partnerships",
    subtitle: "Business Prosperity & Brand Alignments",
    description: "In business, timing and naming are everything. Learn how major multinational companies use planetary consonants to build worldwide brand resonance. Discover the simple steps to calculate your corporate trade name and ensure your founding partnerships are highly compatible.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'hqdefault'),
    category: "Business Guidance",
    collection: ["business-guidance", "trending", "popular"],
    instructor: "Raajeev Singh Chauhann",
    duration: "16:22",
    publishedDate: "2026-01-28",
    language: "Hindi",
    tags: ["Corporate Brand Power", "Partnership Compatibility", "Chaldean Names", "Launch Dates"],
    featured: true,
    difficulty: "Intermediate",
    visibility: "public",
    priority: 95,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 88000,
    watchTime: 1440000,
    likes: 6500,
    learnings: [
      "The core letters that carry extreme wealth frequencies in business names.",
      "How to align your trade name to the industry category's planetary lord.",
      "Detecting hidden partner friction before signing incorporation structures.",
      "Selecting high-prosperity launch dates based on moon phases and planetary hours."
    ],
    relatedCourseId: "c5",
    relatedCourseName: "Business Numerology Strategic Consulting",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20rebrand%20my%20business."
  },
  {
    id: "RcmLxAECJAc-relations",
    title: "Harmonizing Planetary Frequencies in Relationships",
    subtitle: "Chaldean Compatibility Solutions",
    description: "When relationship friction arises, it's often a clash of active planetary numbers. Raajeev Singh Chauhann demonstrates how to calculate your compatibility grid and use peaceful Vedic non-destructive remedies to cultivate harmony, mutual support, and communication.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'hqdefault'),
    category: "Relationship Guidance",
    collection: ["relationship-guidance"],
    instructor: "Raajeev Singh Chauhann",
    duration: "13:40",
    publishedDate: "2026-04-05",
    language: "Hindi",
    tags: ["Relationship Numerology", "Compatibility Remediations", "Communication Keys"],
    featured: false,
    difficulty: "Beginner",
    visibility: "public",
    priority: 60,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 74000,
    watchTime: 1010000,
    likes: 5400,
    learnings: [
      "Find the exact numbers that govern communication and passive empathy.",
      "Why relationship friction is often a reflection of active spatial direction imbalances.",
      "Using gentle water-energy corrects to reduce excessive fiery numbers.",
      "How to resolve grid conflicts using simple daily mutual resonance exercises."
    ],
    relatedCourseId: "c1",
    relatedCourseName: "Complete Chaldean Numerology Masterclass",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20need%20relationship%20harmony."
  },
  {
    id: "RcmLxAECJAc-transformation",
    title: "The Ultimate Guide to Cellular Transformation & Remedial Healing",
    subtitle: "Vedic Crystal Science and Gemstone Therapy",
    description: "True healing is an energetic shift. This masterclass connects Vedic gemstone crystalline structure, planetary frequencies, and subconscious habits. See how simple adjustments to your external filters can prompt a massive positive upgrade in health, focus, and life prosperity.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'maxresdefault'),
    category: "Life Transformation",
    collection: ["editors-picks", "trending", "popular"],
    instructor: "Raajeev Singh Chauhann",
    duration: "22:15",
    publishedDate: "2026-06-14",
    language: "Hindi",
    tags: ["Cellular Resonance", "Vedic Gemstone Crystals", "Remedial Upgrades", "Energy Chakras"],
    featured: true,
    difficulty: "Advanced",
    visibility: "public",
    priority: 96,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 210000,
    watchTime: 4670000,
    likes: 18200,
    learnings: [
      "How natural gemstones capture and funnel solar planetary spectrums into the skin.",
      "Why wearing the wrong gemstone can cause unexpected emotional spikes.",
      "The role of complete, deep cellular detoxification during planetary phase shifts.",
      "Mapping your physical body's energy chakras to specific Chaldean numbers."
    ],
    relatedCourseId: "c1",
    relatedCourseName: "Complete Chaldean Numerology Masterclass",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20am%20ready%20for%20life%20transformation."
  },
  {
    id: "RcmLxAECJAc-webinar",
    title: "Chaldean Numerology Live Webinar: Interactive Destiny Grid Mapping",
    subtitle: "Interactive Group Webinar Session",
    description: "Re-watch our latest interactive LEO Family live webinar. Raajeev Singh Chauhann conducts live calculations for students, mapping their destiny grids on the digital board and offering precise remedial corrections in real-time.",
    youtubeUrl: "https://youtube.com/watch?v=RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'maxresdefault'),
    category: "Webinars",
    collection: ["webinars", "popular", "trending"],
    instructor: "Raajeev Singh Chauhann",
    duration: "1:42:10",
    publishedDate: "2026-07-01",
    language: "Hindi",
    tags: ["Chaldean Live Grid", "Student Calculations", "Spiritual Webinar Session", "Q&A"],
    featured: true,
    isWebinar: true,
    difficulty: "Intermediate",
    visibility: "public",
    priority: 92,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 310000,
    watchTime: 31620000,
    likes: 29400,
    learnings: [
      "Observe live grid drawing and how planetary vacancies are analyzed.",
      "The immediate effects of combining missing numbers with proper Vedic stones.",
      "Real-time student Q&As covering mobile numerology combination frequencies.",
      "Exclusive announcements regarding our upcoming 12-Week Academy courses."
    ],
    relatedCourseId: "c1",
    relatedCourseName: "Complete Chaldean Numerology Masterclass",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20register%20for%20the%20next%20Live%20Webinar."
  },

  // CLIENT SUCCESS STORIES / REVIEWS (TRANSFORMED TO MEDIA ITEMS)
  {
    id: "RcmLxAECJAc-reviews1",
    title: "Priya Sharma's Ultimate Spiritual Name Correction Breakthrough",
    subtitle: "Film Producer Breakthrough Story",
    description: "Priya Sharma details how simple changes to her active name spelling and professional signature unlocked major opportunities in her film production career. Within 4 months of her custom correction, she signed her first major multi-crore project after a 2-year struggle.",
    youtubeUrl: "https://youtube.com/shorts/RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'maxresdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "student-reviews", "popular", "trending"],
    speaker: "Priya Sharma",
    location: "Mumbai, India",
    duration: "4 Mins",
    publishedDate: "2026-06-01",
    language: "English",
    tags: ["Name Correction", "Chaldean Numerology", "Film Industry", "Success Stories"],
    featured: true,
    visibility: "public",
    priority: 99,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 12450,
    watchTime: 49800,
    likes: 890,
    stars: 5,
    courseName: "Name Correction Alignment",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20correct%20my%20Name%20vibrations."
  },
  {
    id: "73_3gXp9x8g",
    title: "Corporate Vastu Alignment for Singhal Logistics & Factory Layout",
    subtitle: "Industrial Non-Destructive Solutions Success",
    description: "Harmonized an active industrial manufacturing plant with non-destructive copper and gemstone implant remedies, boosting throughput by 34% in 90 days. Amit Singhal details the profound boost in worker safety and monthly profitability.",
    youtubeUrl: "https://youtube.com/watch?v=73_3gXp9x8g",
    youtubeId: "73_3gXp9x8g",
    thumbnail: getYoutubeThumbnail("73_3gXp9x8g", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "vastu", "popular"],
    speaker: "Amit Singhal",
    location: "New Delhi, India",
    duration: "12 Mins",
    publishedDate: "2026-05-15",
    language: "Hindi",
    tags: ["Vastu Correction", "Corporate Vastu", "Non-Destructive Solutions", "Industrial Success"],
    featured: true,
    visibility: "public",
    priority: 94,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 8900,
    watchTime: 106800,
    likes: 420,
    stars: 5,
    courseName: "Corporate Vastu",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20am%20interested%20in%20Factory%20Vastu."
  },
  {
    id: "dQw4w9WgXcQ",
    title: "Business Numerology Mastery: Revamping Brand Spelling & Value",
    subtitle: "E-Commerce Startup Scaling",
    description: "E-Commerce founder Rohan aligned his active business legal name to a harmonious number 5 vibration, resulting in record-breaking organic growth and viral branding within weeks of the adjustment.",
    youtubeUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: getYoutubeThumbnail("dQw4w9WgXcQ", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "business-guidance"],
    speaker: "Rohan Shah",
    location: "Singapore",
    duration: "6 Mins",
    publishedDate: "2026-07-02",
    language: "English",
    tags: ["Business Numerology", "Brand Alignment", "Abundance", "Chaldean Names"],
    featured: false,
    visibility: "public",
    priority: 88,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 15300,
    watchTime: 91800,
    likes: 1220,
    stars: 5,
    courseName: "Business Numerology",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20align%20my%20business%20brand."
  },
  {
    id: "9bZkp7q19f0",
    title: "Vedic Astrology career predictions and planetary dasha calculation",
    subtitle: "Precision Career Transition Success",
    description: "A comprehensive astrological consultation mapped out the precise dasha transition, helping Dr. Chauhan time his medical clinic launch with perfect precision, mitigating major financial obstacles.",
    youtubeUrl: "https://youtube.com/watch?v=9bZkp7q19f0",
    youtubeId: "9bZkp7q19f0",
    thumbnail: getYoutubeThumbnail("9bZkp7q19f0", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "astrology", "editors-picks"],
    speaker: "Dr. Rajesh Chauhan",
    location: "London, UK",
    duration: "8 Mins",
    publishedDate: "2026-04-18",
    language: "English",
    tags: ["Vedic Astrology", "Planetary Dasha", "Career Transition", "Clinical Launch"],
    featured: true,
    visibility: "public",
    priority: 91,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 6200,
    watchTime: 49600,
    likes: 310,
    stars: 5,
    courseName: "Vedic Astrology Reading",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20a%20Vedic%20Astrology%20Reading."
  },
  {
    id: "yvD-C03p_1Q",
    title: "Spouse Compatibility & Chaldean Relationship Alignment Blueprint",
    subtitle: "Domestic Peace & Love Restoration",
    description: "Aligning relationship frequencies using compound numbers 24 and 37. Cleared deep-seated domestic stress and created a loving home dynamic through simple daily rituals.",
    youtubeUrl: "https://youtube.com/watch?v=yvD-C03p_1Q",
    youtubeId: "yvD-C03p_1Q",
    thumbnail: getYoutubeThumbnail("yvD-C03p_1Q", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "relationship-guidance"],
    speaker: "Kiran & Ritu Rao",
    location: "Jaipur, India",
    duration: "10 Mins",
    publishedDate: "2026-06-25",
    language: "Hindi",
    tags: ["Relationships", "Spouse Compatibility", "Domestic Harmony", "Chaldean Remediations"],
    featured: false,
    visibility: "public",
    priority: 84,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 4100,
    watchTime: 41000,
    likes: 190,
    stars: 5,
    courseName: "Compatibility Analysis",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20need%20relationship%20harmony%20guidance."
  },
  {
    id: "3AtDnEC4zak",
    title: "Chaldean Numerology Course Review: A Professional Tarot Reader's Story",
    subtitle: "Spiritual Practice Upgrade",
    description: "Preeti details how joining Raajeev Sir's professional academy closed the structural gaps in her Tarot consultations, creating a multi-faceted spiritual coaching practice and doubling client retention.",
    youtubeUrl: "https://youtube.com/shorts/3AtDnEC4zak",
    youtubeId: "3AtDnEC4zak",
    thumbnail: getYoutubeThumbnail("3AtDnEC4zak", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["student-reviews", "numerology-masterclass"],
    speaker: "Preeti Deshmukh",
    location: "Pune, India",
    duration: "3 Mins",
    publishedDate: "2026-05-28",
    language: "Hindi",
    tags: ["Academy Review", "Alumni Testimonial", "Tarot Reading", "Chaldean Certification"],
    featured: false,
    visibility: "public",
    priority: 86,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 18200,
    watchTime: 54600,
    likes: 950,
    stars: 5,
    courseName: "Academy Professional Course",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20join%20the%20Academy."
  },
  {
    id: "E8P8_sR_7w8",
    title: "Signature Geometry and Wealth Frequency Attractor Masterclass Review",
    subtitle: "Pitch Performance & Capital Attraction",
    description: "How learning the sacred geometry of signatures from Raajeev Singh Chauhann revolutionized Arjun's investment firm pitch performance and attracted global venture capital.",
    youtubeUrl: "https://youtube.com/watch?v=E8P8_sR_7w8",
    youtubeId: "E8P8_sR_7w8",
    thumbnail: getYoutubeThumbnail("E8P8_sR_7w8", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "motivation", "trending"],
    speaker: "Arjun Singhania",
    location: "Singapore",
    duration: "5 Mins",
    publishedDate: "2026-07-10",
    language: "English",
    tags: ["Signature Geometry", "Wealth Frequency", "Pitch Alignments", "Capital Attraction"],
    featured: true,
    visibility: "public",
    priority: 97,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 14100,
    watchTime: 70500,
    likes: 720,
    stars: 5,
    courseName: "Signature Geometry Mastery",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20to%20optimize%20my%20Signature%20Geometry."
  },
  {
    id: "FvV_pP4_G7o",
    title: "Diaphragmatic Breathing Loops and Daily Meditation Practice",
    subtitle: "Subconscious Calm Loop Review",
    description: "Aanya shares her profound inner calm and stress-relief transformation after incorporating Raajeev Sir's guided diaphragmatic loops with high-vibrational mudras, restoring career focus.",
    youtubeUrl: "https://youtube.com/watch?v=FvV_pP4_G7o",
    youtubeId: "FvV_pP4_G7o",
    thumbnail: getYoutubeThumbnail("FvV_pP4_G7o", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "meditation"],
    speaker: "Aanya Mehta",
    location: "Bengaluru, India",
    duration: "9 Mins",
    publishedDate: "2026-06-12",
    language: "Hindi",
    tags: ["Meditation", "Breathing Loops", "Vedic Sadhana", "Inner Tranquility"],
    featured: false,
    visibility: "public",
    priority: 83,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 3100,
    watchTime: 27900,
    likes: 140,
    stars: 5,
    courseName: "Guided Breathwork Practice",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20guided%20meditation."
  },
  {
    id: "mdfNIdgYvUo",
    title: "Vastu Correction Without Demolition for Modern Apartments",
    subtitle: "Healed Apartment Cuts Story",
    description: "Vikram explains how his home's North-East structural cuts were completely healed using copper wire implants, restoring sleep patterns and mental tranquility.",
    youtubeUrl: "https://youtube.com/watch?v=mdfNIdgYvUo",
    youtubeId: "mdfNIdgYvUo",
    thumbnail: getYoutubeThumbnail("mdfNIdgYvUo", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "vastu", "trending"],
    speaker: "Vikram Malhotra",
    location: "Mumbai, India",
    duration: "7 Mins",
    publishedDate: "2026-03-30",
    language: "Hindi",
    tags: ["Vastu Correction", "Apartment Vastu", "Cuts Corrections", "Non-Destructive"],
    featured: false,
    visibility: "public",
    priority: 87,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 5400,
    watchTime: 37800,
    likes: 210,
    stars: 5,
    courseName: "Residential Vastu Alignment",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20need%20Apartment%20Vastu%20advice."
  },
  {
    id: "P_m_V7wX2P0",
    title: "Chaldean Grid Analysis: Restructuring Personal Destinies",
    subtitle: "Chaldean Science Success Story",
    description: "Edward details how aligning his date of birth grids with custom signature and telephone corrections unlocked blocked income streams and improved mental focus.",
    youtubeUrl: "https://youtube.com/shorts/P_m_V7wX2P0",
    youtubeId: "P_m_V7wX2P0",
    thumbnail: getYoutubeThumbnail("P_m_V7wX2P0", 'hqdefault'),
    category: "Student Success Stories",
    collection: ["student-reviews", "numerology-masterclass"],
    speaker: "Edward Harrison",
    location: "San Francisco, USA",
    duration: "4 Mins",
    publishedDate: "2026-04-05",
    language: "English",
    tags: ["Chaldean Science", "Numerology Grids", "Personal Destiny", "Global Graduate"],
    featured: false,
    visibility: "public",
    priority: 85,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 2900,
    watchTime: 11600,
    likes: 180,
    stars: 5,
    courseName: "Chaldean Numerology",
    consultationLink: "https://wa.me/919953713176?text=Hi%20Raajeev%20ji,%20I%20want%20Chaldean%20Grid%20Analysis."
  },

  // MOBILE SHORTS / QUICK INTERACTION CLIPS
  {
    id: "short-r1",
    title: "Priya Sharma on Film Production Name Correct Resonance",
    description: "How Priya corrected her film firm spelling and received investors within four months.",
    youtubeUrl: "https://youtube.com/shorts/RcmLxAECJAc",
    youtubeId: "RcmLxAECJAc",
    thumbnail: getYoutubeThumbnail("RcmLxAECJAc", 'mqdefault'),
    category: "Student Success Stories",
    collection: ["success-stories", "editors-picks"],
    speaker: "Priya Sharma",
    location: "Mumbai, India",
    duration: "0:59",
    publishedDate: "2026-06-01",
    language: "English",
    tags: ["Shorts", "Name Spellings", "Film Finance"],
    isShort: true,
    visibility: "public",
    priority: 50,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 24500,
    watchTime: 12250,
    likes: 1840,
    courseName: "Name Correction"
  },
  {
    id: "short-r2",
    title: "Anand Verma on Corporate Vastu factory boosts",
    description: "Vastu factory throughput increased 45% by shifting main entry alignments and stabilizing copper poles.",
    youtubeUrl: "https://youtube.com/shorts/73_3gXp9x8g",
    youtubeId: "73_3gXp9x8g",
    thumbnail: getYoutubeThumbnail("73_3gXp9x8g", 'mqdefault'),
    category: "Vastu",
    collection: ["vastu", "trending"],
    speaker: "Anand Verma",
    location: "New Delhi, India",
    duration: "0:58",
    publishedDate: "2026-04-12",
    language: "Hindi",
    tags: ["Shorts", "Factory Vastu", "Copper Remedies"],
    isShort: true,
    visibility: "public",
    priority: 45,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 18200,
    watchTime: 9100,
    likes: 1220,
    courseName: "Corporate Vastu"
  },
  {
    id: "short-r3",
    title: "Dr. Kabir Roy on Business Mobile Combinations",
    description: "Changed clinical office phone number to high-vibrational Mercury alignment to double bookings.",
    youtubeUrl: "https://youtube.com/shorts/P_m_V7wX2P0",
    youtubeId: "P_m_V7wX2P0",
    thumbnail: getYoutubeThumbnail("P_m_V7wX2P0", 'mqdefault'),
    category: "Free Numerology Classes",
    collection: ["free-classes", "trending"],
    speaker: "Dr. Kabir Roy",
    location: "Kolkata, India",
    duration: "0:55",
    publishedDate: "2026-03-24",
    language: "Hindi",
    tags: ["Shorts", "Mobile Numerology", "Mercury Alignment"],
    isShort: true,
    visibility: "public",
    priority: 40,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 12900,
    watchTime: 6450,
    likes: 980,
    courseName: "Mobile Numerology"
  },
  {
    id: "short-r4",
    title: "Elena Rostova on Career transition to Numerology coach",
    description: "Transitioned from corporate fatigue to active, glowing tarot and Chaldean coach in London.",
    youtubeUrl: "https://youtube.com/shorts/3AtDnEC4zak",
    youtubeId: "3AtDnEC4zak",
    thumbnail: getYoutubeThumbnail("3AtDnEC4zak", 'mqdefault'),
    category: "Student Success Stories",
    collection: ["student-reviews", "editors-picks"],
    speaker: "Elena Rostova",
    location: "London, UK",
    duration: "0:52",
    publishedDate: "2026-05-18",
    language: "English",
    tags: ["Shorts", "Numerology Coach", "Spiritual Job"],
    isShort: true,
    visibility: "public",
    priority: 35,
    createdAt: DEFAULT_NOW,
    updatedAt: DEFAULT_NOW,
    viewCount: 31400,
    watchTime: 15700,
    likes: 2450,
    courseName: "Chaldean Science"
  }
];
